- .travis.yml
- appveyor.yml
Include the acceptance:local rake task in travis and appveyor testing.
> (maint) Add local acceptance tests to Github CI

- README.md
(See here for README rendered on Github: https://github.com/james-stocks/pdk/tree/badges )
> (maint) Add CI badges to README

- README.md
> (maint) Add hints for gem installation

- .travis.yml
- Gemfile
- Rakefile
- appveyor.yml
- lib/pdk/cli/exec.rb
- spec/acceptance/bundle_management_spec.rb
- spec/acceptance/cli_spec.rb
- spec/acceptance/new_class_spec.rb
- spec/acceptance/new_module_spec.rb
- spec/spec_helper_acceptance.rb
work in progress on adding bundle management acceptance tests, extracted from #62
> (SDK-269) Add acceptance tests for bundle management.

- spec/acceptance/validate_ruby_spec.rb
> (SDK-247) Add tests for rubocop target selection

- .rubocop.yml
- .rubocop_todo.yml
- spec/cli/option_normalizer_spec.rb
- spec/cli/option_validator_spec.rb
- spec/cli/validate_spec.rb
- spec/generators/puppet_class_spec.rb
- spec/generators/puppet_object_spec.rb
- spec/logger_spec.rb
- spec/template_file_spec.rb
- spec/validate_spec.rb
These are all I feel comfortable doing right now. The rest of the changes will mess with in progress PRs and can wait until things have quietened down.
> Cleanup rubocop todos

- lib/pdk/cli/exec.rb
- lib/pdk/util/bundler.rb
- spec/util/bundler_spec.rb
> (MAINT) Various CLI::Exec improvements and updates

- lib/pdk/report/event.rb
> (MAINT) Add support for stacktrace to Report::Event class

- README.md
- lib/pdk/cli/validate.rb
Updated to show run specific validators and how to specify targets
> (maint) Update validate CLI help text & README

- CHANGELOG.md
- README.md
- lib/pdk/version.rb
Also includes 0.3.0 release prep, for testing purposes.
> (maint) Add release instructions

- README.md
> (maint) Remove incorrect space character in README

- Rakefile
- lib/pdk/cli/exec.rb
Relates to https://github.com/puppetlabs/puppet-sdk-vanagon/pull/19
> (maint) Changes sdk references to pdk

- README.md
> (maint) fix `new module` description in README

- CHANGELOG.md
- lib/pdk/version.rb
Hopefully for the last time, bump master to 0.5.0.pre! :)
> (MAINT) Bump to 0.5.0.pre

- CONTRIBUTING.md
- README.md
This both avoids confusion, and makes the content easier to discover.
> (maint) Move contributor's notes to separate file

- lib/pdk/version.rb
Bumps master to 0.6.0.pre, I also created a maintenance branch for 0.5.x
> (MAINT) Bump version to 0.6.0.pre

- Gemfile
- Rakefile
- lib/pdk/answer_file.rb
- lib/pdk/generators/puppet_object.rb
Fixes two YARD warnings as well.
> (MAINT) Add YARD gem and rake task

- spec/spec_helper.rb
Not 100% if this will work in CI but we'll see in a minute!
> (MAINT) Don't check coverage on gitignored files

- CHANGELOG.md
- lib/pdk/version.rb
> (MAINT) Release prep for 1.0.0

- pdk.gemspec
This version contains a bugfix for Windows 7.
> (PDK-461) Update childprocess to current version

- lib/pdk/generators/puppet_object.rb
- lib/pdk/generators/task.rb
```
david@davids:~/git/pdk/foo$ ~/git/pdk/bin/pdk new task bar2
pdk (INFO): Creating '/home/david/git/pdk/foo/tasks/bar2.sh' from template.
pdk (INFO): Creating '/home/david/git/pdk/foo/tasks/bar2.json' from template.
david@davids:~/git/pdk/foo$
```
> (PDK-577) Add info line that task metadata was also generated

- lib/pdk/cli.rb
- lib/pdk/cli/convert.rb
- lib/pdk/cli/util.rb
- lib/pdk/generators/module.rb
- lib/pdk/module/convert.rb
- spec/unit/pdk/cli/convert_spec.rb
Ready to start plugging functionality in to.
> (PDK-621) Implement a skeleton `pdk convert` command

- lib/pdk/generate/module.rb
- lib/pdk/module/convert.rb
- lib/pdk/module/metadata.rb
- spec/unit/pdk/module/convert_spec.rb
I didn't add any acceptance tests for this as there doesn't seem much point until the command is more fleshed out (any acceptance tests I write now would have to be rewritten once the diffing & confirmation logic is in place).
> (PDK-627) Support for generating/updating metadata.json during convert

- lib/pdk/module/convert.rb
Request for user to read diffing info before proceeding.
> Additional user prompt

- lib/pdk/module/convert.rb
> (maint) Add/update template metadata on convert

- lib/pdk/module/convert.rb
- spec/unit/pdk/module/convert_spec.rb
This updates the output of convert slightly to be more user friendly.
```
$ pdk convert
------------Files to be added-----------
.gitlab-ci.yml
.pmtignore
.yardopts
appveyor.yml
spec/default_facts.yml
----------Files to be modified----------
metadata.json
.gitignore
.rubocop.yml
.travis.yml
Gemfile
Rakefile
spec/spec_helper.rb
----------------------------------------
You can find detailed differences in convert_report.txt.
pdk (INFO): Module conversion is a potentially destructive action. Please ensure that you have committed your module to a version control system or have a backup, and review the changes above before continuing.
Do you want to continue and make these changes to your module? Yes
[✔] Resolving Gemfile dependencies.
------------Convert completed-----------
5 files added, 7 …
```
> (maint) Some tweaks to improve UX.

- lib/pdk/module/metadata.rb
- spec/unit/pdk/module/convert_spec.rb
Because it doesn't convert to JSON automatically.
> (PDK-729) Remove Set usage in metadata

- lib/pdk/cli.rb
- lib/pdk/cli/update.rb
- lib/pdk/module/update.rb
- spec/unit/pdk/cli/update_spec.rb
Basic CLI wireframe for `pdk update`, ready to be fleshed out with functionality.
> (PDK-771) Wireframe `pdk update` CLI

- lib/pdk/cli/exec.rb
- lib/pdk/module/templatedir.rb
- lib/pdk/util.rb
- lib/pdk/util/git.rb
- spec/acceptance/support/in_a_new_module.rb
- spec/unit/pdk/generate/module_spec.rb
- spec/unit/pdk/module/template_dir_spec.rb
- spec/unit/pdk/util/git_spec.rb
- spec/unit/pdk/util_spec.rb
May be worth adding unit tests for the new helper methods...
> (MAINT) Refactor templatedir path_or_url calculation

- package-testing/spec/package/unit_test_a_new_module_spec.rb
Fix the package tests to accommodate more default operating systems in
metadata.json.
> (maint) Fix package tests

- package-testing/spec/package/airgapped_usage_spec.rb
- package-testing/spec/package/validate_a_new_module_spec.rb
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/job/platform_pdk_pdk-int-sys-testing_master/502/
> (maint) Fix package specs for template-ref changes

- lib/pdk/module/metadata.rb
- spec/acceptance/new_module_spec.rb
- spec/acceptance/test_unit_spec.rb
- spec/unit/pdk/generate/module_spec.rb
Reverts puppetlabs/pdk#682 until facterdb is updated and released with fact sets for the latest operating systems.
> Revert "(PDK-1366) Update default operatingsystem versions"

- lib/pdk/module/metadata.rb
- spec/acceptance/new_module_spec.rb
- spec/acceptance/test_unit_spec.rb
- spec/unit/pdk/generate/module_spec.rb
> (PDK-1366) Update default operatingsystem versions

- README.md
removing an incomplete sentence and an article in front of PDK
> (docs) minor fixups to README

- lib/pdk/util/puppet_version.rb
* The refactor makes the method a bit easier to read
by memonizing the variable in an or condition.
> (maint) Refactors method to use block assignment

- package-testing/spec/package/unit_test_a_new_module_spec.rb
- package-testing/spec/package/update_module_spec.rb
Will link Jenkins result when it's done.
> (PDK-680) Update package tests for interactive `pdk test unit`

- appveyor.yml
- lib/pdk/util/ruby_version.rb
- spec/acceptance/bundle_spec.rb
- spec/unit/pdk/util/ruby_version_spec.rb
See #744 
Opening this as a PR to see how it does with Travis tests.
> (MAINT) Refactor how gem_path to bundler is calculated

- lib/pdk/util.rb
- lib/pdk/util/windows/file.rb
- spec/unit/pdk/util_spec.rb
This reverts commit 10736a4e4536c53c10c86b3f287193ee15bf6994.
> Revert "(PDK-1590) Use short-name for PDK Package base directory on Windows

- lib/pdk/util/changelog_generator.rb
- spec/unit/pdk/util/changelog_generator_spec.rb
> (#855) Use correct namespace for external Bundler call

- docs/customizing_module_config.md
- docs/pdk.ditamap
- docs/pdk.md
- docs/pdk_building_module_packages.md
- docs/pdk_converting_modules.md
- docs/pdk_creating_modules.md
- docs/pdk_install.md
- docs/pdk_known_issues.md
- docs/pdk_overview.md
- docs/pdk_reference.md
- docs/pdk_release_notes.md
- docs/pdk_testing.md
- docs/pdk_troubleshooting.md
- docs/pdk_updating_modules.md
- docs/pdk_upgrading.md
- docs/release_notes_pdk.md
> Adding PDK docs

- CODEOWNERS
> Revert "(MAINT) Add Heston as code owner for docs subdirectory"

- docs/pdk_install.md
- lib/pdk/module/metadata.rb
- spec/acceptance/new_module_spec.rb
- spec/unit/pdk/generate/module_spec.rb
- spec/unit/pdk/module/metadata_spec.rb
Update various usages of the Debian version to the current stable version. Also remove Debian 8, which is EOL.
> update to Debian 10 and remove Debian 8

- package-testing/spec/package/update_module_spec.rb
This should clear up some of the integration testing issues.
> (maint) update packaging test to use up-to-date versions of the modules

- package-testing/spec/package/support/install_pdk.rb
- pdk.gemspec
paired with https://github.com/puppetlabs/pdk-vanagon/pull/284
> (PDK-1041) Use diff-lcs 1.4.4

- spec/acceptance/convert_spec.rb
- spec/acceptance/new_test_spec.rb
- spec/acceptance/report_spec.rb
- spec/acceptance/template_ref_spec.rb
- spec/acceptance/validate_all_spec.rb
- spec/acceptance/validate_puppet_spec.rb
Closes #1168
This PR fixes some syntax errors that were causing lots of failures in the acceptance tests.
> Fix Acceptance Tests

- docs/customizing_module_config.md
- docs/pdk_creating_modules.md
- docs/pdk_overview.md
As per https://github.com/voxpupuli/puppet-syntax description, it does templates and hiera yaml too
> Adding more to description of puppet-syntax

- lib/pdk/version.rb
- package-testing/Gemfile
- package-testing/spec/package/version_selection_spec.rb
This PR contains the necessary work for a 2.6.0 release of PDK.
> (CONT-422) PDK v2.6.0

- CHANGELOG.md
- docs/release_notes_pdk.md
This commit updates release notes for pdk 2.6.0 .
> (CONT-422) - PDK 2.6.0 Release Notes

- lib/pdk/version.rb
This commit bumps PDKs gem version to 2.7.0.
> (CONT-644) Bump gem version

- lib/pdk/version.rb
This change bumps PDK to 2.7.1 and PDK Templates to 2.7.4.
> (CONT-762) Bump versions

- lib/pdk/cli/util.rb
- spec/unit/pdk/cli/util_spec.rb
> (maint) Update minor typo

- .github/workflows/nightly.yml
- docs/pdk.ditamap
- lib/pdk/util/changelog_generator.rb
- spec/support/packaged_install.rb
- spec/unit/pdk/cli/build_spec.rb
- spec/unit/pdk/cli/env_spec.rb
- spec/unit/pdk/cli/exec/command_spec.rb
- spec/unit/pdk/cli/exec/interactive_command_spec.rb
- spec/unit/pdk/cli/release_spec.rb
- spec/unit/pdk/cli/update_spec.rb
- spec/unit/pdk/cli/util_spec.rb
- spec/unit/pdk/generate/module_spec.rb
- spec/unit/pdk/generate/puppet_object_spec.rb
- spec/unit/pdk/module/convert_spec.rb
- spec/unit/pdk/module/release_spec.rb
- spec/unit/pdk/module/update_spec.rb
- spec/unit/pdk/util/bundler_spec.rb
- spec/unit/pdk/util/git_spec.rb
- spec/unit/pdk/util/ruby_version_spec.rb
- spec/unit/pdk/util/template_uri_spec.rb
- spec/unit/pdk/util/vendored_file_spec.rb
- spec/unit/pdk/validate/external_command_validator_spec.rb
- spec/unit/pdk/validate/internal_ruby_validator_spec.rb
- spec/unit/pdk/validate/validator_group_spec.rb
> (maint) - update pdk.ditamap version

- CONTRIBUTING.md
(CAT-343) Audit modules and tools for references to travis. Removed all needless references to travis.
pdk version: `3.0.0`
> pdksync - (CAT-343) Audit modules and tools for references to travis. Removed all needless references to travis.

- docs/pdk.ditamap
> (maint) - reinstate pdk 2.x docs

- docs/pdk.ditamap
> (CAT-1333) - Remove 2.x from ditamap

- spec/acceptance/build_spec.rb
- spec/acceptance/convert_spec.rb
- spec/acceptance/new_class_spec.rb
- spec/acceptance/new_defined_type_spec.rb
- spec/acceptance/new_fact_spec.rb
- spec/acceptance/new_function_spec.rb
- spec/acceptance/new_provider_spec.rb
- spec/acceptance/new_test_spec.rb
- spec/acceptance/new_transport_spec.rb
- spec/acceptance/support/it_requires_running_in_a_module.rb
- spec/acceptance/test_unit_spec.rb
- spec/acceptance/update_spec.rb
- spec/acceptance/validate_all_spec.rb
- spec/acceptance/validate_metadata_spec.rb
- spec/acceptance/validate_puppet_spec.rb
- spec/acceptance/validate_ruby_spec.rb
- spec/acceptance/validate_tasks_spec.rb
- spec/unit/pdk/config/json_schema_namespace_spec.rb
- spec/unit/pdk/config/json_schema_setting_spec.rb
- spec/unit/pdk/config/json_with_schema_spec.rb
- spec/unit/pdk/config/yaml_with_schema_spec.rb
- spec/unit/pdk/module/convert_spec.rb
- spec/unit/pdk/util_spec.rb
Fix for violation of rubocop rules `RSpec/MetadataStyle`
> (RUBO) rubocop `RSpec/MetadataStyle` fix

- docs/pdk_overview.md
> (PUPDOC-5439) Add Trademark icon

- Gemfile
> (maint) - add stricter puppetlabs_spec_helper dependency

- package-testing/spec/package/version_selection_spec.rb
Update Puppet versions in Integration tests to newest major release.
> (CAT-270) Adjusting expected Puppet/Ruby versions

- Gemfile
> (maint) - bump puppetlabs_spec_helper to 7.x

- docs/release_notes_pdk.md
Simple PR to update PDK site documentation to include information about our latest release.
> (CAT-1614) Update site docs with release notes

- package-testing/spec/package/support/serverspec_monkeypatch.rb
- spec/unit/pdk/config/namespace_spec.rb
> (maint) - rubocop fixes

- pdk.gemspec
> (CAT-1703) Convert concurrent-ruby from a pin to a pessimistic constraint

- .github/workflows/mend.yml
> (maint) - Run mend scanning on installed PDK package

- lib/pdk/version.rb
Any changes made to the pdk-templates generated Gemfile need to be brought into the PDK between releases in order for the tests to function as they should.
> (CAT-1697) Bring in new template version

- lib/pdk/version.rb
Any changes made to the pdk-templates generated Gemfile need to be brought into the PDK between releases in order for the tests to function as they should.
> (MAINT) Bring in new template version

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
> (maint) - add puppet version input to workflows

- docs/release_notes_pdk.md
> (CAT-1801) Update release docs

- package-testing/spec/package/airgapped_usage_spec.rb
- package-testing/spec/package/support/spec_utils.rb
- package-testing/spec/package/validate_a_new_module_spec.rb
Correct test changes to resolve failures that where occuring.
> (CAT-1832) Fix test failures

- .github/workflows/labeller.yml
> (maint) Update labeller.yml from pull_request_type to pull_request

- .github/workflows/labeller.yml
> Revert "(maint) Update labeller.yml from pull_request_type to pull_request"

- docs/pdk_install.md
Updating the install documentation to more accurately reflect the supported operating systems
> (CAT-1988) Update the Supported Operating systems to be accurate

- docs/pdk_known_issues.md
> (MAINT) Addition of known issue to docs

- lib/pdk/util/vendored_file.rb
Update code based on changes suggested here: https://github.com/puppetlabs/pdk/pull/1396#discussion_r1769072419
> (CAT-2007) Update http setting cert to setting ca_file

- pdk.gemspec
Updating to keep in line with dependencies in other Puppet related products.
> (CAT-2141) Update `json-schema` dependency

- spec/acceptance/template_ref_spec.rb
> (CAT-2159) Update template-ref used in tests to resolve failures

- docs/release_notes_pdk.md
> (DOC) Update release_notes_pdk.md

- lib/pdk/version.rb
> (MAINT) Update TEMPLATE_REF for testing purposes

- docs/pdk_known_issues.md
> (CAT-2148) Update known template issue with additional information

- lib/pdk/util/template_uri.rb
> (CAT-2148) Update template error message to reference known issues

- package-testing/spec/package/add_gem_to_module_spec.rb
- package-testing/spec/package/airgapped_usage_spec.rb
- package-testing/spec/package/unprivileged_user_spec.rb
- package-testing/spec/package/validate_a_new_module_spec.rb
> (CAT-2241) Update tests to account for known issue

- CONTRIBUTING.md
Small change to remove some outdated intructions.
> (MAINT) Removing outdated instructions
