lib/pdk/cli/util/option_validator.rb
spec/cli/option_validator_spec.rb

Following up on #48, this PR relaxes the data type validation to allow non-standard data types to be used.

Relax data type validation to warn when non-standard types used

---

lib/pdk/generators/module.rb
lib/pdk/module/metadata.rb

Populates the `name` (and by extension `author`) metadata defaults before optionally invoking the interview, this way the metadata without interview will match the metadata if you just hit enter to all the questions in the interview.
Also, the default value for the summary field has been changed from `nil` to an empty string (same as `source`) because it is listed in [the documentation](https://docs.puppet.com/puppet/4.10/modules_metadata.html) as a required value.
This should clear up the pending acceptance test in #58

(SDK-262) Populate default metadata to match interview defaults

---

.gitignore
Rakefile
ext/build_defaults.yml
spec/spec_helper_acceptance.rb

A couple of changes to the repo that make it work with our standard CI tooling.
Specifically, this PR adds a packaging bootstrapping task; and changes the environment variable that acceptance testing uses to identify a package version to test against.

(SDK-218) Prepare for CI tests against built packages

---

.travis.yml
appveyor.yml
lib/pdk/cli/exec.rb
lib/pdk/cli/tests/unit.rb
lib/pdk/tests/unit.rb
lib/pdk/util.rb
lib/pdk/util/bundler.rb
pdk.gemspec
spec/acceptance/cli_spec.rb
spec/util/bundler_spec.rb

This seems to be working pretty well at this point.
I added a conditional to disable the spinner stuff on Windows for now because there are some special considerations for making control sequences work under cmd/ps. Definitely solvable but probably more appropriate for a subsequent release.
There are a couple PRs backed up in the packaging repo to make this all work with packaged builds, but the paths etc. are all up to date with where things will eventually be.

(SDK-261) Manage basic bundler operations for module dev

---

Rakefile
spec/acceptance/new_class_spec.rb
spec/spec_helper_acceptance.rb

Surely these will be broken on non-linux, but I need to get it off this
workstation.

(SDK-197) add acceptance tests for new class command

---

lib/pdk/util.rb
lib/pdk/validators/puppet/puppet_lint.rb

Fixes a typo from #71 and ensures that we don't hit an exception due to nil default target value.

(FIXUP) Fixes module_root typo and validate nil handling

---

lib/pdk/validators/base_validator.rb
lib/pdk/validators/metadata.rb
lib/pdk/validators/puppet/puppet_lint.rb
lib/pdk/validators/puppet/puppet_parser.rb
lib/pdk/validators/ruby/rubocop.rb

Refactors the validators further so that parsing targets from the CLI and invoking the command are part of the base class. This way, the only thing each validator needs to do is implement a method to build an array of arguments to pass to the command

(SDK-244) Add rubocop validator

---

lib/pdk/util.rb

Change cache location from APPDATA to LOCALAPPDATA
This makes it local data and not roaming.

(maint) Windows cache folder should not be roaming

---

Gemfile
pdk.gemspec
spec/spec_helper_acceptance.rb

I had to do this to get acceptance tests running in my environment, opening the PR to see if it passes Travis/Appveyor.

(FIXUP) Add a GEM_PATH for bundler when running acceptance tests

---

lib/pdk/cli/exec.rb

This provides a better API for setting up sub processes than the existing class/module method based approach.
`PDK::CLI::Exec.execute` is still provided for backwards compatibility and nothing has yet been updated to directly use the new `Command` class.

(MAINT) Create a class-based subprocess executor.

---

lib/pdk/cli.rb
lib/pdk/generators/module.rb
lib/pdk/util/version.rb
lib/pdk/version.rb

To allow easy checking and reporting of the current pdk version, {{--version}} should report the installed version of PDK, as well as the vanagon build SHA from a built package or the git ref from a local git repo.

(SDK-274) Adds --version option

---

lib/pdk/util/bundler.rb
spec/util/bundler_spec.rb

Adds a guard into `PDK::Util::Bundle.ensure_bundle!` so that it more or less idempotent. We'll need to be calling this in multiple places when we shell out to commands inside the bundle and although this method won't actually change anything on subsequent executions as it is, it will cause the spinner to be displayed multiple times.

(maint) Guard PDK::Util::Bundle.ensure_bundle! to only run once

---

.rubocop.yml
lib/pdk/cli/exec.rb
lib/pdk/module/templatedir.rb
lib/pdk/util.rb
lib/puppet/util/windows.rb
lib/puppet/util/windows/api_types.rb
lib/puppet/util/windows/file.rb
lib/puppet/util/windows/string.rb
spec/acceptance/bundle_management_spec.rb
spec/spec_helper_acceptance.rb

PDK::Util.make_tmpdir_name might return a short (8.3) path on Windows.
This commits adds a canonical path method to allow assurance of using
the full path.
This fixes module generation on Windows; previously PDK was failing to
match C:\Users\Administrator and C:\Users\ADMIN~1

(maint) Expand Windows 8.3 paths in templatedir

---

Gemfile
lib/pdk/cli/validate.rb
lib/pdk/generators/module.rb
lib/pdk/validators/base_validator.rb
lib/pdk/validators/metadata.rb
lib/pdk/validators/puppet/puppet_lint.rb
lib/pdk/validators/puppet/puppet_parser.rb
lib/pdk/validators/puppet_validator.rb
lib/pdk/validators/ruby/rubocop.rb
spec/cli/validate_spec.rb

Adds validation for puppet syntax using `puppet parser validate`.
This PR also includes various cleanups and refactoring of the validation handlers.

(SDK-137) Adds Puppet Parser syntax validation

---

Gemfile
lib/pdk/report.rb
lib/pdk/report/event.rb
spec/acceptance/support/have_xpath.rb
spec/acceptance/validate_ruby_spec.rb
spec/fixtures/JUnit.xsd
spec/pdk/report/event_spec.rb
spec/spec_helper_acceptance.rb

Adds tests for both `text` and `junit` formats.
It's hard to find an official spec for the JUnit XML format as everyone who implements it releases their own different version (except for the Apache Foundation, of course, who didn't release one), but I believe the one I've found the original XSD. In order to comply with the XSD, I've had to make a few minor changes to our JUnit formatter to implement attributes and elements that the docs I was originally following had marked as optional.
I ended up implementing my own RSpec matcher for XML as the best existing gem I could find (rspec-xml) hasn't been updated for RSpec 3 and throws deprecation notices around when using the matchers it provides.

(SDK-245) Add acceptance tests for the output of the ruby validator

---

spec/acceptance/new_class_spec.rb
spec/acceptance/test_spec.rb

Adds an acceptance spec for using pdk new class when not inside a module folder.
Adds a pending acceptance spec for using pdk test unit when not inside a module folder.
Does not address pdk validate when not inside a module folder - SDK-277 is an existing bug for this.

(SDK-190) Acceptance tests for using commands outside module folder

---

lib/pdk/report.rb
lib/pdk/report/event.rb
spec/fixtures/JUnit.xsd

Documents that skipped tests will include rspec pending examples.
Adds skipped tests to our XML reports
Updates the test fixture XML schema to allow for skipped tests

(maint) Support for skipped/pending tests

---

README.md
lib/pdk/cli/validate.rb
lib/pdk/validators/puppet/puppet_lint.rb
lib/pdk/validators/ruby/rubocop.rb
spec/acceptance/support/in_a_new_module.rb
spec/acceptance/validate_puppet_spec.rb
spec/acceptance/validate_ruby_spec.rb

This will just silently no-op for validators that don't support auto correction. There's no acceptance tests for puppet-lint integration at the moment, so I've only added an acceptance test for auto-correcting rubocop violations.

(SDK-285) Add --auto-correct flag to validators that support it

---

lib/pdk/cli/exec.rb
lib/pdk/util/bundler.rb
lib/pdk/validators/base_validator.rb

Currently, the output of the validators is overly noisy. Each validator needs to ensure the presence of its appropriate binstub, which prints a "Checking for required Bundler binstubs" spinner for each validator.
```
$ ../bin/pdk validate
pdk (INFO): Running all available validators...
[✔] Checking for missing Gemfile dependencies
[✔] Checking for required Bundler binstubs
[✔] Checking metadata.json
[✔] Checking for required Bundler binstubs
[✔] Checking Puppet manifest style
[✔] Checking for required Bundler binstubs
[✔] Checking Puppet manifest syntax
[✔] Checking for required Bundler binstubs
[✔] Checking Ruby code style
```
This change instead makes the binstub generation silent unless it fails, as binstub generation is quick and is an implementation detail that the user shouldn't …

(maint) Make binstub generation quiet unless it fails

---

lib/pdk/cli/test/unit.rb
lib/pdk/tests/unit.rb
spec/acceptance/test_unit_spec.rb

Implements the _pdk test unit --list_ option that outputs a list of the module's spec tests

(SDK-148) Implement pdk test unit --list

---

spec/acceptance/bundle_management_spec.rb
spec/acceptance/new_class_spec.rb
spec/acceptance/validate_all_spec.rb
spec/acceptance/validate_metadata_spec.rb
spec/acceptance/validate_puppet_spec.rb
spec/acceptance/validate_ruby_spec.rb

SDK-294 is a bug where one acceptance test fails to create 'foo' as a module folder, in spite of the previous acceptance test apparently deleting it.
This commit does not directly fix that issue; but instead has acceptance tests use unique folder names instead of all using 'foo'

(SDK-294) Avoid module name conflict in acceptance tests.

---

lib/pdk/report.rb
spec/acceptance/report_spec.rb

There is a bug where writing reports to a file isn't working so `--format=text:report.txt` or `--format=junit:report.xml` is doing nothing, results are not being written anywhere. This fixes that.
Also adds some sanity acceptance tests to make sure reports are being written to the right place.

(SDK-297) Fixes writing reports to a file

---

Gemfile
lib/pdk/util/bundler.rb
spec/acceptance/support/in_a_new_module.rb
spec/spec_helper_acceptance.rb

2 performance improvements for the PDK itself:
* Fetch the bundler load path entry from `Gem.loaded_specs` rather than shelling out to `bundle show bundler`
* Avoid regenerating binstubs that already exist. We can't just remove the `--force` because bundler returns != 0 if the named binstubs already exist. There are gems out there whose executables don't match the gem name so this short circuit won't work for them, but it handles the majority of cases. 
1 performance improvement for the acceptance tests:
* Pull down the pdk-module-template repo into a temporary directory at the start of the run and use that local repo as the template when creating modules during tests, avoiding subsequent network traffic.
These 3 changes dropped the execution time of `rake acceptance:local` on my machine …

(maint) Performance improvements

---

lib/pdk/module/metadata.rb

A new release of metadata-json-lint was pushed out a couple of days ago that included https://github.com/voxpupuli/metadata-json-lint/pull/68 which causes the data types for the metadata values to get validated. This is causing our acceptance tests to fail because we include `nil` values (translated to `null` in JSON) in our generated metadata.json.
This change compacts the metadata hash to remove those keys with `nil` values (optional metadata elements like issues_url) before generating the JSON structure.

(maint) Remove nil values from metadata before generating JSON

---

lib/pdk/validators/base_validator.rb
lib/pdk/validators/metadata.rb
lib/pdk/validators/puppet/puppet_lint.rb
lib/pdk/validators/puppet/puppet_syntax.rb
lib/pdk/validators/ruby/rubocop.rb
spec/acceptance/validate_all_spec.rb
spec/acceptance/validate_metadata_spec.rb

In order to accommodate this functionality, I needed to refactor the base validator a bit so that we can optionally invoke the validator once per target (as metadata-json-lint only supports testing a single file).

(SDK-296) Allow target selection for the metadata validator

---

spec/acceptance/support/have_junit_testcase.rb
spec/acceptance/support/have_junit_testsuite.rb
spec/acceptance/validate_metadata_spec.rb
spec/acceptance/validate_puppet_spec.rb
spec/acceptance/validate_ruby_spec.rb

Just an idea that I was pondering tonight. I know that I am biased towards RSpec magic more than is probably healthy, so I just wanted to put this out there for the rest of you to consider. I'm not entirely sold on it and am happy to stick with the xpath matcher if that's the group consensus :)

(idea) More expressive RSpec matchers for JUnit XML content

---

lib/pdk/cli.rb
lib/pdk/cli/util/option_normalizer.rb
lib/pdk/cli/util/option_validator.rb
spec/pdk/cli_spec.rb

Changes the option validation code for `--format` over to using `PDK::CLI::Util::OptionNormalizer.report_formats` which raises a `PDK::CLI::FatalError` exception when given an invalid report format name, which is then automatically handled by the CLI and presented to the user in a nicer format than a stack trace.

(SDK-298) Handle exception raised when an invalid report format is specified on the CLI

---

lib/pdk/cli/util/option_normalizer.rb
lib/pdk/report.rb
spec/cli/option_normalizer_spec.rb
spec/cli/validate_spec.rb

* Changes `PDK::CLI::Util::OptionNormalizer.report_formats` to return the default target rather than `nil` if no target has been specified. With that we can get rid of the extra defaulting in the report methods themselves as we'll never be sending a nil value.
* Adds unit test for report specification in `PDK::CLI::Validate`, which should bring us to 100% coverage of this class.

(maint) Finish off PDK::CLI::Validate unit tests

---

.rubocop_todo.yml
lib/pdk/validate.rb
lib/pdk/validators/metadata/metadata_json_lint.rb
lib/pdk/validators/metadata/metadata_syntax.rb
lib/pdk/validators/metadata_validator.rb
pdk.gemspec
spec/cli/validate_spec.rb
spec/pdk/validate/metadata_json_lint_spec.rb
spec/pdk/validate/metadata_syntax_spec.rb
spec/pdk/validate/metadata_validator_spec.rb
spec/spec_helper.rb

Adds a new validator (`metadata-syntax`) that uses json_pure to ensure the JSON files are syntactically correct before `PDK::Validate::MetadataJSONLint` is invoked. I'm forcing it to use json_pure for this because it provides much more useful error messages than the C extension.

(SDK-299) Check metadata.json syntax before linting

---

README.md

Removes the following info, which I am given to understand is not accurate:
* Creating a module initializes Git for you
* You can create a resource provider with pdk
I also added a sentence clarification, but it's pretty small.

removes some incorrect info from README

---

.gitignore
Gemfile
Rakefile
package-testing/config/options.rb
package-testing/lib/helper.rb
package-testing/lib/pdk/pdk_helper.rb
package-testing/post/000_archive_results.rb
package-testing/pre/000_install_package.rb
package-testing/pre/010_update_rubygems_cert.rb
package-testing/pre/020_copy_tests_to_sut.rb
package-testing/tests/run_acceptance.rb

The _acceptance:package_ command will now:
1. Install package on VM
2. Copy acceptance tests over to VM
3. (Using the ruby and git vendored with pdk package) bundle install acceptance test dependencies
4. Invoke rspec on the VM
5. On completion; copy the rspec results back to the machine that executed _acceptance:package_
Still a number of things to fix; but I'd like to review and commit the basis of this work then finish off the details.
Still TODO:
- Acceptance tests do not completely pass on either Linux or Windows
- Need to add junit XML formatter to rspec so the test results can be used by CI server
- Need some assurance (I'm not sure in advance how CI will be set up) that the version of tests that are run is the same pdk ref as the package being tested - currently tests may fail if …

(SDK-275) Run tests against VM with package install

---

README.md
Rakefile
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/none.yml

Some tidy up around acceptance:
* Remove Rakefile code relating to old vagrant-based acceptance testing (this is a leftover from before the acceptance:local task was available)
* Remove spec/acceptance/nodesets directory that was also intended for vagrant-based acceptance testing.
* Update README.md with guidance on the available testing rake tasks.

Acceptance tidy-up

---

Rakefile
package-testing/lib/pdk/pdk_helper.rb
spec/acceptance/package_spec.rb
spec/spec_helper_acceptance.rb

Ensure that acceptance tests against a package install execute the installed pdk and NOT pdk from source
Also updates the beaker pre-suite to use the new install path /opt/puppetlabs/pdk instead of sdk

(maint) Improvements to acceptance testing packages

---

lib/pdk.rb
lib/pdk/answer_file.rb
lib/pdk/cli.rb
lib/pdk/cli/util/interview.rb
lib/pdk/generators/module.rb
spec/acceptance/support/in_a_new_module.rb
spec/generators/module_spec.rb
spec/pdk/answer_file_spec.rb

Adds the `PDK::AnswerFile` class to handle reading and saving user-supplied answers to questions.
The responses from the module interview for the following questions are saved and used as the default values for new modules:
* Forge username
* Author name
* License
If the license is specified on the command line with `--license`, then that value is saved to the answer file as well.
Additionally, if the user specifies their own module template using `--template-url`, that value is also saved and used automatically for any subsequent modules.
I had to add a hidden option to the CLI (`--answer-file`) in order to run the acceptance tests with clean answer files. Not sure if we want to make this option visible or not (my gut reaction is to keep it hidden unless there is a need for it).

(SDK-305) Answer file to cache module interview answers, template-url etc

---

lib/pdk/cli/exec.rb

When running commands in module context, we always want to use our private
ruby. Especially bundler's binstubs are using ruby from the PATH, which
led to weird failures, as the multiple rubies would not agree on installed
gems, etc.

(SDK-319) force usage of our ruby

---

appveyor.yml
lib/pdk/cli/exec.rb
spec/acceptance/test_unit_spec.rb

This changes the method for resolving the installation path of a user
managed bundler gem to make it not depend on bundler itself.
Also cleans up the management of subprocess PATH from SDK-319.

(#158) (#166) Resolve issue loading bundler from gem installs

---

pdk.gemspec

Got a report of someone installing the PDK gem on Ruby 2.0.0 which threw syntax errors when trying to run any `pdk` commands. As 2.1.9 is the earliest Ruby version we're testing, we should specify that in the gemspec too.

(maint) Add 2.1.9 as the minimum required ruby version in the gemspec

---

lib/pdk/cli/exec.rb

* `bundle install --path` ignores all "system" installed gems and causes unnecessary package installs
* `bundle install` (without --path) installs into GEM_HOME, which by default is non-user writeable
To still use the pre-installed packages, but allow folks to install additional gems
this sets GEM_HOME to the user's cachedir, and put all other cache locations onto GEM_PATH
See https://stackoverflow.com/a/11277228 for background
This still requires that the exact required gem versions are available in
package_cachedir.

(SDK-331) allow additional gems to be installed

---

spec/acceptance/new_class_spec.rb

SDK-322 was a bug where 0 examples ran for a new class due to a facter release leaving us with 0 facts for rspec-puppet-facts to use.
This commit adds an acceptance test to ensure that a new class will have more than 0 working examples when pdk test unit is run.

(SDK-322) Acceptance test for spec tests of new class

---

lib/pdk/util/bundler.rb
spec/acceptance/bundle_management_spec.rb
spec/util/bundler_spec.rb

Since this runs pretty much every time and doesn't have potential for taking very long (as opposed to `bundle lock` or `bundle install`) I think it's more appropriate as a debug log message.

(MAINT) Remove spinner for `bundle check` command

---

lib/pdk/cli/exec.rb
pdk.gemspec

As reported in #137, when a user installs the PDK gem on a fresh machine that
does not have git installed, they get an unhelpful message about git failing
with a misleading reference to files inside the PDK.
With this change, we instead check that the binary being called exists before
attempting to execute it and raise an error suggesting that the user needs to
install the appropriate package before trying again.
This won't be a big issue once we have system packages going out, but it
provides a nicer initial experience for users installing the gem.
```
root@stretch:~# pdk new module foo --skip-interview
pdk (INFO): Creating new module: foo
pdk (FATAL): Unable to find `git`. Check that it is installed and try again.
root@stretch:~# apt-get install -y git
[output trimmed]
root@stretch:~# …
```

(#137) Nicer response when binary doesn't exist

---

lib/pdk/generators/module.rb
spec/generators/module_spec.rb

Does an initial check before starting the interview, so that we don't waste the user's time. Also rescues `Errno::EACCES` from `FileUtils.mv` in the event that the permissions change between the pre-run check and the module generation.

(SDK-317) Ensure parent of 'pdk new module' is writable before generation

---

README.md
lib/pdk/cli/new/module.rb
spec/unit/cli/new/module_spec.rb

This option doesn't currently do anything as it's waiting on getting libgit2 into the package (which is blocked on devkit in the windows packages). We should remove this option for now as it suggests functionality that doesn't exist.

(maint) Remove unused vcs option from 'pdk new module'

---

README.md

This updates the readme to better explain how the pdk uses PowerShell and what
configuration needs to be done post install. It also adds some minimal suggestions
on troublshooting the pdk PowerShell module not being loaded in a PowerShell shell.
This also replaces the link to exectution policies with a current link, the previous
link was for PowerShell 1.0 and had a tenth of the information needed for current
versions.

Update PowerShell install instructions

---

lib/pdk/validators/base_validator.rb

A fix requested by @DavidS in #144

(MAINT) Replace #sort.last with #max

---

lib/pdk/generators/module.rb

Cyan is less likely to conflict with a users background color than the
default (bright black).
Users can also avoid this by enabling their terminal's 'minimum
contrast' feature.

(SDK-323) Change color of default answer to cyan

---

lib/pdk/generators/module.rb
spec/unit/pdk/generate/module_spec.rb

Was adding a spec for this failure case and noticed that we're not displaying the message for the caught exception here.

(maint) Expose message when FileUtils.mkdir_p fails during module generation

---

spec/spec_helper.rb
spec/unit/pdk_spec.rb

Simple test, just to finish off the coverage of that class. Slight change to how the stubbed logger context is included so that it can be optionally disabled in order to test the actual behaviour of `PDK.logger`.

(maint) Add unit test for PDK.logger

---

CHANGELOG.md
Gemfile
Rakefile

Since skywinder/github-changelog-generator#550 was merged, we can switch to the upstream repo.
Once a new version is released we can drop the git reference altogether.
This also includes a minor config change to make the rake task work, and the current output to show the minimal changes to the CHANGELOG file's format, and no content changes in the historical entries.

(MAINT) Update to official master of github-changelog-generator

---

lib/pdk/validators/metadata/metadata_json_lint.rb
spec/unit/pdk/validate/metadata_json_lint_spec.rb

metadata-json-lint 2.0.2 changed the behavior around open-ended dependencies...

(MAINT) Add --strict-dependencies to metadata-json-lint invocation

---

.rubocop.yml
CONTRIBUTING.md
Gemfile
Rakefile
package-testing/.gitignore
package-testing/Gemfile
package-testing/Rakefile
package-testing/config/options.rb
spec/acceptance/package_spec.rb
spec/spec_helper_acceptance.rb

To isolate package testing from the codebase (specifically pdk's Gemfile), package-testing should have its own Gemfile.
This PR also has a commit to remove a couple of 'package testing' leftovers from the spec/ folder

Give beaker package tests their own Gemfile

---

lib/pdk/cli/util/interview.rb
spec/unit/pdk/cli/bundle_spec.rb
spec/unit/pdk/cli/errors_spec.rb
spec/unit/pdk/cli/exec_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/util/interview_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/module/template_dir_spec.rb
spec/unit/pdk/test/unit_spec.rb
spec/unit/pdk/util/version_spec.rb
spec/unit/pdk/validate/base_validator_spec.rb
spec/unit/pdk/version_spec.rb

Coveralls appears to only count coverage of code required by spec tests.
This commit adds at least a placeholder for all our code files; to set a baseline for Coveralls

Unit test baseline

---

lib/pdk/cli/exec.rb
lib/pdk/cli/test/unit.rb
lib/pdk/tests/unit.rb
spec/unit/pdk/test/unit_spec.rb

Waiting for a new version of puppetlabs_spec_helper for the updated rake task
I now believe it's waiting for a new version of puppet-module-gems
v0.1.0 of puppet-module-gems has been released

(SDK-312) Add option --parallel to `pdk test unit`

---

lib/pdk/tests/unit.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/test/unit_spec.rb

When there are no tests `pdk test unit` outputs `No examples found`, but
the parallel_tests gem aborts with an error and does not output JSON.
This catches that error situation and standardizes the output.
To reproduce simply make a new module with `pdk new module` and run `pdk test unit` and `pdk test unit --parallel`

(MAINT) Fix fatal error in test unit --parallel

---

lib/pdk/tests/unit.rb
lib/pdk/util.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/util_spec.rb

`pdk test unit` was using a pattern defined in puppetlabs_spec_helper while `pdk test unit --list` was using no pattern.
This commit updates the --list option to use a puppetlabs_spec_helper rake task so it uses the same pattern.

(PDK-373) Make test unit --list consistent with test unit

---

CONTRIBUTING.md
package-testing/Rakefile
package-testing/pre/000_install_package.rb

This change lets you run the package-based acceptance tests but on a package you have built locally instead of requiring it to be on the builds server.
For example:
```
LOCAL_PKG=/path/to/package/pdk-0.5.0.0.11.g612fd91-1.el7.x86_64.rpm TEST_TARGET=redhat7-64workstation. bundle exec rake acceptance
```
I found this greatly reduced my cycle times for testing acceptance test changes that also required code changes.
Thoughts? Is there a more standard way to do this?

(MAINT) Add ability to test locally built package with beaker

---

package-testing/config/options.rb
package-testing/tests/validate_a_new_module.rb

When running in Jenkins CI, beaker needs to be told what key(s) to load.
The current tests work fine on our workstations but fail to connect to VMs in Jenkins CI.

Package testing: beaker needs to have keys configured

---

lib/pdk/module/templatedir.rb

By adding quoting and a slash, the directory name becomes easily
recognisable as such.

(MAINT) Improve moduleroot error message

---

.travis.yml
Gemfile
Rakefile
spec/spec_helper.rb

This rake task will enable coverage tracking, execute the specs, and print a summary at the bottom of the test run.

(PDK-390) Implement spec:coverage rake task

---

lib/pdk/module/metadata.rb
spec/acceptance/test_unit_spec.rb

Provide working defaults until https://tickets.puppetlabs.com/browse/PDK-383 is finished.

(maint) update Windows defaults

---

.rubocop.yml
package-testing/Gemfile
package-testing/Rakefile
package-testing/config/options.rb

Currently rubocop does not cover the package-testing folder due to what was thought to be a bug: https://github.com/bbatsov/rubocop/issues/4640
From that bug report; it appears that our rubocop config should have additional wildcard patterns to exclude hidden files.
This PR adds those patterns, and then fixes all the rubocop issues in the package-testing folder.

Enable rubocop for package-testing folder

---

lib/pdk/cli/validate.rb
spec/acceptance/validate_all_spec.rb

'pdk validate' should run all top-level validators even if one
of the validators produces an error.

(SDK-325) Validate all should run all validators

---

CONTRIBUTING.md
package-testing/Gemfile
package-testing/Rakefile
package-testing/pre/000_install_package.rb

Add package install for OSX (beaker does not have a helper for this, yet. See https://tickets.puppetlabs.com/browse/BKR-1109 for having a single helper for all platforms implemented).
I'm unhappy with the amount of code here when beaker and vanagon should provide a 2-liner method to get a .dmg from the build server and install it on the workstation host.
Tested against a number of builds (including per-commit builds and tag builds). Also tested that this works with the LOCAL_PKG option to point to a local .dmg file instead of one on the build server

(PDK-385) Support package testing on OSX

---

lib/pdk/generators/module.rb
spec/unit/pdk/generate/module_spec.rb

Suprisingly, the library doesn't do this by default. By providing our own
validation block, we can make it retry when it receives an invalid response
rather than throwing an exception.

(PDK-407) Validate module interview confirmation answer

---

lib/pdk/generators/module.rb
lib/pdk/module/metadata.rb
lib/pdk/module/templatedir.rb
spec/acceptance/new_module_spec.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/module/template_dir_spec.rb

-Adds a puppet requirement to metadata.json
-Adds generating a skeleton README.md when generating new module
-Adds generating a skeleton CHANGELOG.md when generating new module
Requires https://github.com/puppetlabs/pdk-module-template/pull/24

(PDK-388, PDK-392) New module generation improvements.

---

lib/pdk/cli/exec.rb
lib/pdk/cli/exec_group.rb
lib/pdk/logger.rb
lib/pdk/validators/metadata/metadata_syntax.rb
spec/unit/pdk/cli/exec/command_spec.rb
spec/unit/pdk/cli/exec_spec.rb
spec/unit/pdk/logger_spec.rb

Disables the spinners if running with `--debug`. We already add a message to the debug log when starting a new process, so I've added another message to the debug log for when the process exits.

(PDK-396) Disable spinners in debug mode

---

lib/pdk/util/bundler.rb
spec/unit/pdk/util/bundler_spec.rb

Output of `bundle check` should go to DEBUG but non-zero exit status for the rest of the bundler commands represent fatal errors.

(PDK-397) Log output of bundler commands at appropriate levels

---

lib/pdk/cli/exec.rb

This is to handle cases where there is not a `.bundle/config` in a module telling bundler what paths to add to `PATH` when running `bundle exec`.

(PDK-406) Add GEM_HOME and GEM_PATH bin dirs to PATH when executing

---

lib/pdk/util/bundler.rb

Set jobs=2 when PDK calls bundle install to allow bundler to install gems in parallel.
It could be set higher than 2 but that might require testing to check it has no issues and even saves any time on workstations with less processing resource.

(maint) Allow bundler to install gems in parallel

---

lib/pdk/cli/validate.rb
lib/pdk/report/event.rb
lib/pdk/validators/base_validator.rb
lib/pdk/validators/metadata/metadata_syntax.rb
lib/pdk/validators/metadata_validator.rb
lib/pdk/validators/puppet/puppet_lint.rb
lib/pdk/validators/puppet/puppet_syntax.rb
lib/pdk/validators/ruby/rubocop.rb
spec/acceptance/report_spec.rb
spec/acceptance/validate_all_spec.rb
spec/acceptance/validate_metadata_spec.rb
spec/acceptance/validate_puppet_spec.rb
spec/acceptance/validate_ruby_spec.rb
spec/support/it_accepts_metadata_json_targets.rb
spec/support/it_accepts_pp_targets.rb
spec/unit/pdk/report/event_spec.rb
spec/unit/pdk/validate/base_validator_spec.rb
spec/unit/pdk/validate/metadata_json_lint_spec.rb
spec/unit/pdk/validate/metadata_syntax_spec.rb
spec/unit/pdk/validate/metadata_validator_spec.rb
spec/unit/pdk/validate/rubocop_spec.rb

Updates validators to handle targets consistently and disallows input of
explicit targets that are incompatible with the validator's defined
filter pattern. Also updates the spinner text to be informative about what
kind of files the validator is validating against.
Relates to #239

(PDK-401, PDK-402, PDK-403, PDK-404) Update validators to handle targets better

---

lib/pdk/cli/util/interview.rb
lib/pdk/monkey_patches.rb

The non-blocking keypress read in the latest version of tty-prompt is causing issues with the module interview on windows - it's not waiting for any input and just using the default value.

(maint) monkey patch TTY::Prompt::Reader::WinConsole to make it blocking

---

lib/pdk/cli/exec.rb
spec/unit/pdk/cli/exec/command_spec.rb

To aid troubleshooting in cases of ruby environment doubts.

(maint) Debug output GEM_HOME and GEM_PATH before executing module commands

---

lib/pdk/generators/module.rb
spec/unit/pdk/generate/module_spec.rb

Upon successful generation of a new module, inform the user:
- that the module has been generated successfully
- where it is located
- what to do next

(PDK-365) Inform and prompt user following new module generate

---

package-testing/lib/pdk/pdk_helper.rb
package-testing/tests/add_gem_to_module.rb
package-testing/tests/pdk_is_on_path.rb

Package tests should expect 'pdk' to be on path and should not use the full path to pdk.

(PDK-446) Package tests should expect pdk to already be on path

---

package-testing/lib/pdk/pdk_helper.rb

Beaker defaults to running commands in a non-interactive /bin/sh session
which means that /etc/profile and other shell setup files are not
sourced. This commit changes our helper method to still run 'pdk'
without an explicit path but do so inside a 'login' session of /bin/bash
so that any profile based PATH changes are in place when the command
runs.

(MAINT) Run package test commands in a login shell

---

lib/pdk/util.rb
lib/pdk/util/windows.rb
spec/acceptance/validate_all_spec.rb

Puppet 5 changed the format of the module definition in Puppet::Util::Windows
from the expanded to condensed format. The downside of this change is that it
means that the requires are now order dependent, as the condensed format does
not define the parent objects if not already defined.
This change abstracts our require of `puppet/util/windows`, allowing us to
define the `Puppet` and `Puppet::Util` modules before requiring
`puppet/util/windows`, fixing the exception caused when `pdk` and `puppet`
exist in the same gemfile.

(PDK-420) Ensure Puppet and Puppet::Util modules are defined

---

lib/pdk/generators/module.rb
spec/acceptance/validate_metadata_spec.rb
spec/unit/pdk/generate/module_spec.rb

Having the stdlib dependency in there, but not in the rspec-puppet fixtures
leads to painful expectations: stdlib functions are available, but using
them in the code leads to test failures. Adding it to the fixtures would
cause the default PDK workflow to require a online connection, so this
instead removes the unforced dependency.

(PDK-450) remove stdlib dependency

---

lib/pdk/cli/new.rb
lib/pdk/cli/new/defined_type.rb
lib/pdk/generate.rb
lib/pdk/generators/defined_type.rb
spec/acceptance/new_defined_type_spec.rb
spec/unit/pdk/cli/new/defined_type_spec.rb
spec/unit/pdk/generate/defined_type_spec.rb

```
NAME
defined_type - Create a new defined type named <name> using given options
USAGE
pdk new defined_type [options] <name>
OPTIONS
--template-url=<value>      Specifies the URL to the template to use
when creating new modules or classes.
(default:
https://github.com/puppetlabs/pdk-module-template)
OPTIONS FOR NEW
-d --debug                     Enable debug output.
-f --format=<value>            Specify desired output format. Valid
formats are 'junit', 'text'. You may also
specify a file to which the formatted
output is sent, for example:
'--format=junit:report.xml'. This option
may be specified multiple times if each
option specifies a distinct target file.
-h --help                      Show help for this command.
--version                   Show version of pdk.
```

(PDK-459) Add defined type generator

---

lib/pdk/generators/puppet_object.rb

```
foo$ ~/git/pdk/bin/pdk new def bar
pdk (FATAL): Unable to generate defined_type; '/home/david/git/pdk/foo/manifests/bar.pp' already exists.
foo$ ~/git/pdk/bin/pdk new class bar
pdk (FATAL): Unable to generate class; '/home/david/git/pdk/foo/manifests/bar.pp' already exists.
foo$
```

(PDK-459) Improve error message when the generation target exists

---

lib/pdk/util/version.rb
spec/unit/pdk/util/version_spec.rb

When there is no target `.git` directory, no need to call git at all.
Also adds more tests to cover everything.

(PDK-461) Make Version.git_ref more forgiving

---

lib/pdk/cli/util/interview.rb
lib/pdk/generators/module.rb
spec/unit/pdk/generate/module_spec.rb

WIP because I need to test this out on windows

(SDK-336) Add operating system question to the new module interview

---

lib/pdk/cli.rb
lib/pdk/cli/bundle.rb
lib/pdk/cli/module.rb
lib/pdk/cli/module/generate.rb
lib/pdk/cli/new/module.rb
lib/pdk/cli/util/command_redirector.rb
lib/pdk/generators/module.rb
spec/unit/cli/module/generate_spec.rb
spec/unit/cli/module_spec.rb
spec/unit/cli/new/module_spec.rb
spec/unit/pdk/cli/util/command_redirector_spec.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/validate/puppet_lint_spec.rb
spec/unit/pdk/validate/rubocop_spec.rb

This new CLI option is meant to mirror the 'puppet module generate' command for experienced module developers used to the old method of generating a module skeleton. This CLI option redirects to 'pdk new module' after an initial prompt confirming the user's intent.

(PDK-370) Adds a 'pdk module generate' redirect to 'pdk new module'.

---

lib/pdk/tests/unit.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/test/unit_spec.rb

Example output for a git clone failure from a bad `.fixtures.yml` entry.
```
asmodean :0: pdk/foo (git:pdk-465-2 → origin {2} U:1 ?:1!)$ ../bin/pdk test unit
[✖] Preparing to run the unit tests.
pdk (ERROR): Could not find semantic_puppet gem, falling back to internal functionality. Version checks may be less robust.
pdk (ERROR): Cloning into 'spec/fixtures/modules/notexist'...
pdk (ERROR): fatal: remote error:
pdk (ERROR):   this/does/not/exist is not a valid repository name
pdk (ERROR):   Email support@github.com for help
pdk (ERROR): rake aborted!
pdk (ERROR): Failed to clone git repository git://github.com/this/does/not/exist.git into spec/fixtures/modules/notexist
pdk (ERROR): /home/tsharpe/.pdk/cache/ruby/2.1.0/gems/puppetlabs_spec_helper-2.3.2/lib/puppetlabs_spec_helper/rake_tasks.r …
```

(PDK-465) Improve output from spec_prep/spec_clean failures

---

lib/pdk/cli.rb
lib/pdk/cli/errors.rb
lib/pdk/cli/new/class.rb
lib/pdk/cli/new/defined_type.rb
lib/pdk/cli/util.rb
lib/pdk/cli/util/option_normalizer.rb
lib/pdk/generators/module.rb
lib/pdk/generators/puppet_object.rb
spec/unit/cli/new/module_spec.rb
spec/unit/pdk/cli/new/class_spec.rb
spec/unit/pdk/cli/new/defined_type_spec.rb
spec/unit/pdk/cli/util/option_normalizer_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/cli_spec.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/generate/puppet_object_spec.rb

Adds a new exception type that should be raised when dealing with user input related problems (like trying to create a class that already exists).
```
asmodean :0: pdk/foo (git:pdk-415 → origin {2} ?:2!)$ ../bin/pdk new class foo
pdk (ERROR): Unable to generate class; '/home/tsharpe/code/puppet/pdk/foo/manifests/init.pp' already exists.
```
`PDK::CLI::FatalError` should still be used when catching and re-raising an exception, as those are almost always fatal errors and should be displayed as such.

(PDK-415) Convert user-input related problems from FATAL to ERROR

---

lib/pdk/report/event.rb
spec/unit/pdk/report/event_spec.rb

Adds the spec description to the output for rspec events, as well as up to 5 lines of context of the failing spec (up to 2 on either side of the failing line).
Example:
```
asmodean :0: pdk/foo (git:sdk-369 {2} U:1 ?:2!)$ ../bin/pdk test unit
[✔] Preparing to run the unit tests.
[✖] Running unit tests.
Evaluated 5 tests in 0.206083208 seconds: 5 failures, 0 pending.
[✔] Cleaning up after running unit tests.
failed: rspec: ./spec/classes/foo_spec.rb:8: expected that the catalogue would not compile but it does
foo on windows-2012-x64 should not compile into a catalogue without dependency cycles
Failure/Error:
let(:facts) { os_facts }
it { is_expected.not_to compile }
end
end
failed: rspec: ./spec/classes/foo_spec.rb:8: expected that the catalogue would not compile but it does
foo on …
```

(PDK-369) Improve error context for pdk test unit failures

---

lib/pdk/cli/exec.rb

Git on Windows doesn't seem to automatically find its component binaries, so we need to add them to the path in order for the vendored git to work properly.

(PDK-502) Add git mingw paths to PATH

---

lib/pdk/validators/base_validator.rb
spec/acceptance/validate_puppet_spec.rb

`Dir.glob` [doesn't support backslash separated paths](https://ruby-doc.org/core-2.2.0/Dir.html#method-c-glob) due to backslashes being used to escape characters, so we convert the ALT_SEPARATORs to SEPARATORs in user supplied paths before using them.

(PDK-555) Handle windows style (backslash separated) paths

---

README.md
lib/pdk/validators/base_validator.rb
lib/pdk/validators/metadata/metadata_json_lint.rb
lib/pdk/validators/metadata/metadata_syntax.rb
lib/pdk/validators/metadata/task_metadata_lint.rb
lib/pdk/validators/metadata_validator.rb
pdk.gemspec
spec/acceptance/validate_all_spec.rb
spec/acceptance/validate_metadata_spec.rb
spec/support/it_accepts_metadata_json_targets.rb
spec/support/it_accepts_pp_targets.rb
spec/unit/pdk/validate/base_validator_spec.rb
spec/unit/pdk/validate/metadata_json_lint_spec.rb
spec/unit/pdk/validate/metadata_validator_spec.rb
spec/unit/pdk/validate/rubocop_spec.rb
spec/unit/pdk/validate/task_metadata_lint_spec.rb

I've refactored the task metadata validation to validate against a json-schema per recommendation/request from @garethr .
This PR also includes functionality to extend the MetadataSyntax validator to validate the tasks JSON as well.

(PDK-470) Validation of task metadata.

---

lib/pdk/cli/bundle.rb

PowerShell evaluates '--' itself and doesn't pass it on to the pdk
function. The backtick stops PowerShell from further argument parsing
and saves the double dash from being gobbled up.
To make it easier to discover by windows users, this also changes the
usage, when run on windows.

(PDK-408) Explain PowerShell escaping for -- on `bundle`

---

lib/pdk/generators/module.rb
spec/unit/pdk/generate/module_spec.rb

To give a fuller experience when looking at a new module, provide
the common directories that people need.
Given that git will happily ignore the empty directories, it's a bit
wishy-washy, but will do as a first iteration for newcomers.

(PDK-479) new module: create examples/, and files/ directory

---

lib/pdk/validators/puppet/puppet_lint.rb
spec/unit/pdk/validate/puppet_lint_spec.rb

When validating a module via `pdk validate`, puppet-lint fails validation for its autoloader_layout check if the module directory is not the exact module name, i.e. if validating an ntp module, puppet-lint passes `/path/ntp` but fails `/path/puppetlabs-ntp`.
This passes the `--relative` argument to puppet-lint to ignore the top-most directory of the module and pass in both of the previous examples. Hopefully this should help with module conversion.
More info: https://github.com/rodjek/puppet-lint/issues/245
and https://github.com/rodjek/puppet-lint/pull/252

Add --relative cli argument for autoload layout testing in puppet-lint

---

package-testing/tests/pdk_help.rb

Rename beaker test file so it reflects what the test actually does.
Remove redundant teardown block.
[skip ci]

(maint) Tidy up package test

---

lib/pdk/generators/module.rb

To raise awareness of the existance of templates, and make it clear
which template is used.

(PDK-594) mention the used template during `new module`

---

Gemfile
lib/pdk/cli/test/unit.rb
lib/pdk/tests/unit.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/test/unit_spec.rb

This PR Improves how `pdk test unit --list` outputs unit test list. It will display a list of test files that contain examples. This output should contain file paths that can then be passed into `--tests=` as a comma-separated list.
This PR also adds a `--verbose` or `-v` option to display more information about the examples in each test file.
```
[~/proj/sdk/test_modules/testmod]$ pdk test unit -h
NAME
unit - Run unit tests.
USAGE
pdk test unit [options]
OPTIONS
--list                     List all available unit test files.
--tests=<value>            Specify a comma-separated list of test
files to run.
-v --verbose                  Outputs more detail.
OPTIONS FOR TEST
-d --debug                    Enable debug output.
-f --format=<value>           Specify desired output format. Valid …
```

(PDK-674) UX Improvement for listing unit test files.

---

lib/pdk/generate/module.rb
lib/pdk/module/templatedir.rb
spec/acceptance/new_module_spec.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/module/template_dir_spec.rb

Required for the new 'convert' functionality - The aim of this update is so that files needed for convert are kept in a default directory,
while new requires additional directories that will be found in the 'moduleroot_init'.

(PDK-626) Templatedir can now handle multiple directories

---

lib/pdk/tests/unit.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/test/unit_spec.rb

(PDK-429) Fix --tests to pass through to unit test handler.

---

lib/pdk/cli/exec.rb
spec/acceptance/report_spec.rb
spec/acceptance/support/with_a_fake_tty.rb
spec/acceptance/test_unit_spec.rb
spec/acceptance/validate_all_spec.rb
spec/acceptance/validate_metadata_spec.rb
spec/acceptance/validate_puppet_spec.rb
spec/acceptance/validate_ruby_spec.rb
spec/unit/pdk/cli/exec/command_spec.rb

Determines if the process is being run interactively by checking if stderr is a TTY and only create the spinners when the PDK is run interactively.
Acceptance tests for this proved to be troublesome as the specinfra exec backend doesn't support creating a PTY. I created a new backend for specinfra but it turns out that Windows doesn't support PTYs anyway, so that had to be thrown away and I've instead gone for an environment variable (h/t to DEBIAN_FRONTEND) to override the TTY check during tests.

(PDK-643) Do not display spinners when not running interactively

---

lib/pdk/tests/unit.rb
spec/unit/pdk/test/unit_spec.rb

The behavour of the parallel_spec rake task in puppetlabs_spec_helper changed in https://github.com/puppetlabs/puppetlabs_spec_helper/pull/216. This PR updates our logic to detect no tests vs fail in `pdk test unit --parallel`.

(maint) Update PDK::Test::Unit.parallel_with_no_tests? for PSH #216 changes

---

lib/pdk/generate/module.rb
spec/unit/pdk/generate/module_spec.rb

Since we are using the interview for convert now it doesn't make sense to talk about generation of modules in the error messages, so I've made them more generic.

Making exit errors generic for interview qs

---

lib/pdk/module/convert.rb
lib/pdk/module/update_manager.rb
pdk.gemspec
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/module/update_manager_spec.rb

Abstracts away the file modification logic into its own class. This will allow
easy reuse for the future `pdk update` as well as a simple interface for
storing the pending changes in memory rather than on disk (less cleanup
required in the event of an interrupt). The presentation/reporting of the changes
has been separated from the logic that makes the changes, so that we can easily
tweak and modify the output as this feature develops.
---
An example where my metadata.json was missing the license field.
```
asmodean :0: pdk/foo (git:master → origin {2} U:3 ?:2!)$ ../bin/pdk convert
pdk (INFO): This is a potentially destructive action. Please ensure that you have committed it to a version control system or have a backup before continuing.
Do you want to continue converting this module? Yes …
```

(PDK-624) Add UpdateManager class to handle making changes to module files

---

lib/pdk/module/templatedir.rb
lib/pdk/util.rb
lib/pdk/util/bundler.rb
lib/pdk/version.rb
spec/unit/pdk/util_spec.rb

For gem installs, we need to make sure they use a compatible
module-template version, similar to what we do for package installs
in our build process. For development, we still want to use the
default git branch.

(PDK-715) Use correct module template branch/ref

---

lib/pdk/cli/convert.rb
lib/pdk/module/convert.rb
spec/unit/pdk/cli/convert_spec.rb

We already ask the user if they want to continue before applying any of the
changes, so we don't really need this one here. The warning about having
a backup has been moved to the confirmation before the changes are applied.

(PDK-722) Remove prompt to continue from start of convert

---

lib/pdk/cli/convert.rb
lib/pdk/cli/util.rb
lib/pdk/generate/module.rb
lib/pdk/module/convert.rb
spec/support/run_outside_module.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/new/class_spec.rb
spec/unit/pdk/cli/new/defined_type_spec.rb
spec/unit/pdk/cli/new/task_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/cli_spec.rb
spec/unit/pdk/module/convert_spec.rb

(PDK 719) Directory layout and metadata fixes during convert

---

lib/pdk/cli/bundle.rb
lib/pdk/cli/module.rb
lib/pdk/cli/module/generate.rb

Since CRI's message about hidden commands is very confusing to users
this commit just unhides everything, and makes it clear that those
subcommands are experimental, or for compatibility purporses only.

(PDK-489) unhide experimental commands

---

CHANGELOG.md
Gemfile
Rakefile

This version contains the label filtering that we need, and adds
more info to the changelog. Since we're maintaining separate release
notes on puppet.com/docs anyways, this seems to be a benefit, as it
gives multiple levels of details. Added a link to the main release notes
to connect them.

(MAINT) Update to released version of GCG

---

lib/pdk/cli/exec.rb
lib/pdk/cli/exec_group.rb
lib/pdk/cli/util.rb
lib/pdk/validate/metadata/metadata_syntax.rb
lib/pdk/validate/metadata/task_metadata_lint.rb
spec/unit/pdk/cli/util_spec.rb

The spinners in `PDK::Validate::MetadataSyntax` and `PDK::Validate::TaskMetadataLint` were missed in the first pass as they don't follow the usual pattern of executing an external command.

(PDK-643) Disable non-exec validator spinners when noninteractive

---

spec/unit/pdk/version_spec.rb

Because this file only contains constants and no runtime code, it
doesn't play well with code coverage as it's evaluated at load time
only. Adding a manual load in the spec works around this.

(maint) Manually load lib/pdk/version.rb in spec

---

lib/pdk/util.rb
spec/unit/pdk/util_spec.rb

Previously, if the user had the old puppetlabs/pdk-module-template URL
saved in their answers.json, PDK would still try to use the old repo but
attempt to reset to the `1.3.0` tag which doesn't exist in the old repo.
This commit starts treating a value matching the old repo URL the same
as if there is no template URL specified so that it uses the new
template URL instead.
Furthermore, if the user had a real custom template repo, we were still
attempting to reset to the `1.3.0` tag which probably won't exist in
their custom repo. After this commit, pdk will only try to reset to the
pinned tag when using the official template repo (or packaged repo).

(PDK-736) Improve handling of old template-url and template-ref

---

lib/pdk/util.rb
lib/pdk/util/git.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/util/git_spec.rb
spec/unit/pdk/util_spec.rb

Checks if the repo pointed to by the saved template-url from the answer file contains valid refs and fall back if it doesn't. `git ls-remote` will return non-zero (or specifically 2) if the remote does not exist or does not contain the specified ref (if supplied).

(PDK-739) Fall back to default template if necessary

---

lib/pdk/version.rb

puppetlabs/pdk-templates should be tagged with the PDK version during release, so we should be able to default this to version, preventing future acceptance test failures like https://travis-ci.org/puppetlabs/pdk/jobs/329178285 where one of the `pdk new module` tests failed due to pdk-templates getting belatedly tagged with 1.3.1.
This test will still fail if pdk-templates gets tagged before the version number is bumped, but that'll be fixed with PDK-718.

(maint) Default PDK::TEMPLATE_REF to PDK::VERSION

---

lib/pdk/cli.rb
lib/pdk/cli/bundle.rb
lib/pdk/cli/convert.rb
lib/pdk/cli/errors.rb
lib/pdk/cli/new/class.rb
lib/pdk/cli/new/defined_type.rb
lib/pdk/cli/new/task.rb
lib/pdk/cli/test/unit.rb
lib/pdk/cli/util.rb
lib/pdk/cli/validate.rb
spec/acceptance/support/it_requires_running_in_a_module.rb
spec/support/run_outside_module.rb
spec/unit/pdk/cli/errors_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb

Refactors `PDK::CLI::ExitWithError` to allow it to take a log level option and then modifies `PDK::CLI::Util.ensure_in_module!` definition and uses to allow the message and level to be customised as needed.

(PDK-552) Soften PDK::CLI::Util.ensure_in_module! error messages

---

lib/pdk/cli.rb
lib/pdk/cli/build.rb
lib/pdk/module/build.rb
spec/unit/pdk/cli/build_spec.rb

So that we have something to start bolting things onto

(PDK-748) Wireframe `pdk build` CLI

---

lib/pdk/cli.rb
lib/pdk/cli/convert.rb
lib/pdk/cli/new/module.rb
lib/pdk/generate/module.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/new/module_spec.rb
spec/unit/pdk/generate/module_spec.rb

PR includes:
- Removes unrequired questions from module interview
- Adds a `--full-interview` option to `new module` to ask all of the questions from the module interview.
- changes the warning about forge username sanitization to a debug msg.

(PDK-550) Removes unrequired questions from module interview

---

lib/pdk/module/build.rb
pdk.gemspec
spec/unit/pdk/module/build_spec.rb

Port of the build code from PMT, with some changes to bring it inline with the PDK and unit tests. Next up, bolt this into the CLI and get some acceptance tests going.

(PDK-758) Initial port & cleanup of the module build code

---

lib/pdk/validate/puppet/puppet_syntax.rb
spec/unit/pdk/validate/puppet_syntax_spec.rb

To prevent any user or system level puppet.conf settings from interfering with the behaviour of the PDK, pass `/dev/null` or `NUL` (depending on the platform) as the puppet.conf when running `puppet parser validate`.

(PDK-575) Run puppet parser validate with an dummy empty puppet.conf

---

lib/pdk/cli/build.rb
lib/pdk/generate/module.rb
lib/pdk/module/build.rb
lib/pdk/module/metadata.rb
spec/unit/pdk/cli/build_spec.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/module/metadata_spec.rb

When the user triggers a module build via the CLI, check for any missing metadata fields (forge specific things like source, issues_url, etc) and interview the user for these specific values.
This PR replaces #417 
Closes #417

(PDK-754) Interview for missing or Forge only metadata before build

---

lib/pdk/module/build.rb
spec/unit/pdk/module/build_spec.rb

pdk will now make sure that if there is no ignore file and if the pkg
target-dir is in the module_dir, then it will add the target-dir
to the ignores list.

(PDK-804) Fixes error in build without ignore file

---

lib/pdk/cli/build.rb
spec/unit/pdk/cli/build_spec.rb

This was something I noticed during the demo today, that the overwrite prompt was the only thing that wasn't prefixed with the standard logger stuff.

(FIXUP) Make `pdk build` overwrite prompt consistent

---

spec/support/exit_with_status.rb
spec/unit/pdk/cli/build_spec.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/module/generate_spec.rb
spec/unit/pdk/cli/new/class_spec.rb
spec/unit/pdk/cli/new/defined_type_spec.rb
spec/unit/pdk/cli/new/module_spec.rb
spec/unit/pdk/cli/new/task_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/update_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/cli_spec.rb
spec/unit/pdk/generate/module_spec.rb

Adds a couple of convenience aliases to the `exit_with_status` matcher introduced in #423 to test the two common cases: exiting 0 (`exit_zero`) and exiting not zero (`exit_nonzero`). Updated the rest of the unit tests to use the new matcher.

(maint) Update unit tests to use exit_zero/exit_nonzero matchers

---

lib/pdk/generate/module.rb

PDK does not correctly validate module names if a module name is not supplied to `pdk new module`.
The user question prompts for a module name but fails to pass underscores as valid.
- `pdk new module test_name` will pass
- `pdk new module` will fail on `test_name` given as the module name.
This update uses the regex [referred to in the docs](https://puppet.com/docs/puppet/5.4/modules_fundamentals.html#module-names) for validating module names. 
I have included a similar error message to the options validation line, while referring to "numbers" as the docs do.

Update validation regex and error message for module name question

---

lib/pdk/module/convert.rb
lib/pdk/module/templatedir.rb
lib/pdk/module/update.rb
spec/acceptance/update_spec.rb
spec/unit/pdk/module/template_dir_spec.rb
spec/unit/pdk/module/update_spec.rb

Fixes two problems:
1) When convert is run and there are removed files, the summary will throw an error because the removed files set is a set of strings and not a set of hashes.
2) When pdk update is run on a tagged template, it needs to be able to compare against a tag vs comparing against branches and sha.

pdk update and convert fixes

---

lib/pdk/module/convert.rb
lib/pdk/module/update.rb
lib/pdk/module/update_manager.rb
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/module/update_spec.rb

Previously, when running pdk update, note how in the second case there were "2 files removed":
```
david@davids:~/git/tmp/bar$ rm -f .travis.yml; ~/git/pdk/bin/pdk update --force
pdk (INFO): Updating david-bar using the template at file:///opt/puppetlabs/pdk/share/cache/pdk-templates.git, from 1.4.1 to master@52adbbb
------------Files to be added-----------
.travis.yml
----------------------------------------
------------Update completed------------
1 files added.
david@davids:~/git/tmp/bar$ rm -f Gemfile ; ~/git/pdk/bin/pdk update --force
pdk (INFO): Updating david-bar using the template at file:///opt/puppetlabs/pdk/share/cache/pdk-templates.git, from 1.4.1 to master@52adbbb
------------Files to be added-----------
Gemfile
----------------------------------------
[✔] Resolving Gemfile …
```

(maint) update: don't mention deleted Gemfile.lock and .bundle/config

---

lib/pdk/cli/module.rb
lib/pdk/cli/module/build.rb
spec/unit/pdk/cli/module/build_spec.rb
spec/unit/pdk/cli/module/generate_spec.rb

This is a UI hint similar to `pdk module generate` to point folks used
to the puppet faces towards the new pdk commands.

(maint) add a `pdk module build` command to point to `pdk build`

---

lib/pdk/cli.rb
lib/pdk/cli/exec.rb
lib/pdk/cli/test/unit.rb
lib/pdk/cli/validate.rb
lib/pdk/util/puppet_version.rb
lib/pdk/util/ruby_version.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb
spec/unit/pdk/util/ruby_version_spec.rb

The important bit: It adds the `--puppet-version` and `--pe-version` options to the `pdk validate` and `pdk test unit` commands (it's a lot of changed lines for such a simple change, but this PR lays a lot of the groundwork for the rest of the puppet & ruby version switching behaviour).
* PE versions are mapped to Puppet versions in a static hash (copied from the forge), though this will eventually be made dynamic.
* `GEM_PATH` and `GEM_HOME` have been extracted from `PDK::CLI::Exec` into a separate class, allowing them to be reused when scanning for available Puppet versions (and eventual ruby version switching).
* Available Puppet versions are determined by scanning `GEM_HOME` and `GEM_PATH` for puppet gemspec files and parsing their contents.
* Puppet version selection will prefer an …

(PDK-785) Add --puppet-version and --pe-version CLI options

---

.travis.yml
Gemfile
appveyor.yml

Also moves "primary" Ruby version in Travis to 2.4.3

(MAINT) Add Ruby 2.5 to Travis and Appveyor config

---

.travis.yml
lib/pdk/module/metadata.rb
lib/pdk/util/puppet_version.rb
lib/pdk/util/ruby_version.rb
spec/unit/pdk/module/metadata_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb
spec/unit/pdk/util/ruby_version_spec.rb

For use when selecting the default Puppet & Ruby version if the user doesn't specify one

(PDK-840) Add PDK::Util::PuppetVersion.from_module_metadata

---

README.md
lib/pdk/cli/bundle.rb
pdk.gemspec

By upgrading to the new version of CRI, the `skip_option_parsing`
call can be used to avoid the previous confusion of bundle vs pdk
options.

(maint) Allow `pdk bundle` to work without `--`

---

lib/pdk/cli/exec.rb
lib/pdk/util.rb
lib/pdk/util/bundler.rb
lib/pdk/util/ruby_version.rb
lib/pdk/util/version.rb
spec/support/packaged_install.rb
spec/unit/pdk/util/bundler_spec.rb
spec/unit/pdk/util/ruby_version_spec.rb

Also refactored the PDK::Util::Bundler unit tests while I was in there, that work is mostly in the second commit but could be smooshed together if it doesn't seem worth keeping separate.

(PDK-921) Update PDK::Util::Bundler helpers to support gem switching

---

lib/pdk/util/bundler.rb
spec/unit/pdk/util/bundler_spec.rb

Due to the way ChildProcess parses arguments we have to pass multiple
gems as distinct arguments instead of a single, space-delimited option.

(MAINT) Fix argument bug with BundleHelper#update_lock!

---

lib/pdk/util/puppet_version.rb
spec/unit/pdk/util/puppet_version_spec.rb

@scotje as discussed in hipchat, this change will allow users to specify just major or major.minor versions which will be converted into the equivalent pessimistic version requirement.
e.g.
* `5` => `~> 5.0`
* `5.3` => `~> 5.3.0`

(maint) Allow users to major or major.minor versions

---

lib/pdk/cli/exec.rb

Leading slashes are a thing and these two were *not* equivalent like I thought. :)

(FIXUP) Revert incorrect path change in PDK::CLI::Exec.bundle_bin

---

lib/pdk/cli/test/unit.rb
lib/pdk/cli/util.rb
lib/pdk/cli/validate.rb
lib/pdk/util.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/util_spec.rb

This will warn a user if their module requires a pdk update, pdk convert, or pdk installation upgrade based on a comparison of the version displayed in their module's metadata and the installed PDK version.

(PDK-904) Warns users of pdk version compatibility 

---

lib/pdk/cli.rb
lib/pdk/cli/bundle.rb
lib/pdk/cli/exec.rb
lib/pdk/cli/test/unit.rb
lib/pdk/cli/util.rb
lib/pdk/cli/validate.rb
lib/pdk/tests/unit.rb
lib/pdk/util/bundler.rb
lib/pdk/util/puppet_version.rb
lib/pdk/util/ruby_version.rb
package-testing/tests/version_selection.rb
spec/acceptance/new_provider_spec.rb
spec/acceptance/report_spec.rb
spec/acceptance/version_changer_spec.rb
spec/spec_helper.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/util/bundler_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

Unless otherwise stated, packaged install stuff requires packages built from the HEAD of master on pdk-vanagon.

(PDK-842) Wire puppet-version and pe-version options into subcommands

---

package-testing/config/options.rb
package-testing/lib/pdk/pdk_helper.rb
package-testing/tests/airgapped_usage.rb
package-testing/tests/version_selection.rb

Incorporates Tim's fixes to the version selection tests to make them more dynamic, adds the "airgapped usage" tests that I was working on, and fixes ENV management for Windows tests.

(MAINT) Fix package tests for version selection and airgapped usage

---

.rubocop.yml
appveyor.yml
lib/pdk/util.rb
lib/pdk/util/puppet_version.rb
lib/pdk/util/vendored_file.rb
lib/pdk/validate/metadata/task_metadata_lint.rb
spec/fixtures/pe_versions.json
spec/spec_helper.rb
spec/unit/pdk/util/puppet_version_spec.rb
spec/unit/pdk/util/vendored_file_spec.rb

This ended up an uglier change than I expected as the format of the JSON object from the forge API changed between the initial implementation and now. I've tried to keep the changes logically separated by commit though for easier reviewing.

(maint) Remove static PE version map from PDK::Util::PuppetVersion

---

lib/pdk/generate/module.rb
spec/unit/pdk/generate/module_spec.rb

This change prevents the metadata interview from re-asking for the module name if the module name contains underscores.

(maint) Allow module name to contain underscores when verifying

---

lib/pdk/cli/bundle.rb
lib/pdk/util/bundler.rb
spec/unit/pdk/util/bundler_spec.rb

@rodjek has volunteered to help me finish this while I work on packaging things 😀

(MAINT) Make Bundler update_lock! helper more resilient

---

appveyor.yml
lib/pdk/util/bundler.rb
spec/unit/pdk/util/bundler_spec.rb

For post-1.5.0 bug bashing consideration.
See https://bugs.ruby-lang.org/issues/11033 for background.
I think this is the cause of our "cert already in hash table" transients in Appveyor as well as some of the issues @glennsarti was encountering in https://tickets.puppetlabs.com/browse/PDK-802
Ruby issue linked above was backported to Ruby 2.3 branch and released in 2.3.5, however Appveyor is still on 2.3.3 for Ruby23.
Inside PDK packages it should only be an issue on the 2.1.9 bundler invocations.

(PDK-802) Work around OpenSSL multi-threading errors when needed

---

package-testing/Gemfile
package-testing/pre/000_install_package.rb

Beaker and beaker-hostgenerator needed to be aware of Ubuntu Bionic and macOS High Sierra.

(MAINT) Bump beaker and beaker-hostgenerator for new platforms

---

lib/pdk/module/metadata.rb
lib/pdk/util/puppet_version.rb
spec/acceptance/convert_spec.rb
spec/unit/pdk/module/metadata_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

When no `metadata.json` exists, `File.file?` can throw nasty exceptions:
```
david@davids:~/git/pdk$ ./bin/pdk bundle list
Traceback (most recent call last):
11: from ./bin/pdk:29:in `<main>'
10: from ./bin/pdk:29:in `load'
9: from /home/david/git/pdk/exe/pdk:6:in `<top (required)>'
8: from /home/david/git/pdk/lib/pdk/cli.rb:18:in `run'
7: from /home/david/gems/ruby/2.5.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
6: from /home/david/gems/ruby/2.5.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
5: from /home/david/gems/ruby/2.5.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
4: from /home/david/git/pdk/lib/pdk/cli/bundle.rb:24:in `block (2 levels) in <module:CLI>'
3: from /home/david/git/pdk/lib/pdk/cli/util.rb:96:in `puppet_from_opts_or_env'
2: from …
```

Change Metadata.from_file to reliably raise

---

lib/pdk/report/event.rb
spec/unit/pdk/report/event_spec.rb

When reading the spec file to provide context around an rspec failure,
first attempt to read the path given for the event, and if that fails
try the same path but relative to the module root.

(PDK-926) Read rspec event context relative to module root

---

lib/pdk/cli/util.rb
spec/unit/pdk/cli/util_spec.rb

The current behaviour if you run `pdk validate` or `pdk test unit` on a module that hasn't been converted to be PDK compatible is to display a warning and attempt to continue anyway.
```
semirhage :0: pdk/foo (git:master → origin ↑10 ?:1!)$ ../bin/pdk validate
pdk (WARN): This module is not PDK compatible. Run `pdk convert` to make it compatible with your version of PDK.
pdk (INFO): Running all available validators...
pdk (INFO): Using Ruby 2.4.4
pdk (INFO): Using Puppet 5.5.1
[✔] Resolving default Gemfile dependencies.
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✔] Checking Ruby code style (**/**.rb).
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).
info: puppet-syntax: ./: …
```

(PDK-809) Exit early if the module is not PDK compatible

---

lib/pdk/util/bundler.rb
spec/unit/pdk/util/bundler_spec.rb

`bundle lock` doesn't have a `--gemfile` option, but you can set `BUNDLE_GEMFILE`.
This commit also sets the target `Gemfile.lock` explicitly just to be safe.

(PDK-979) Set path to Gemfile when invoking `bundle lock`

---

lib/pdk/cli/test/unit.rb
lib/pdk/module/build.rb
lib/pdk/tests/unit.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/module/build_spec.rb
spec/unit/pdk/test/unit_spec.rb

To make the iterative workflow faster, this (along with puppetlabs/puppetlabs_spec_helper#242) changes the behaviour of `pdk test unit` so that it doesn't automatically remove the downloaded fixtures after the test run. For CI purposes (or if you really want to slow things down) `--clean-fixtures` can be passed to `pdk test unit` to restore the old behaviour.
```
semirhage :0: pdk/foo (git:master → origin U:2 ?:1!)$ rm -rf spec/fixtures/modules/
semirhage :0: pdk/foo (git:master → origin U:2 ?:1!)$ time ../bin/pdk test unit
pdk (INFO): Using Ruby 2.4.4
pdk (INFO): Using Puppet 5.5.1
[✔] Preparing to run the unit tests.
[✔] Running unit tests.
Evaluated 4 tests in 0.149583489 seconds: 0 failures, 0 pending.
real	0m32.575s
user	0m8.906s
sys	0m1.328s
semirhage :0: pdk/foo (git:master → …
```

(PDK-636) Make fixture cleaning optional

---

lib/pdk/cli/exec_group.rb
lib/pdk/validate/base_validator.rb
spec/unit/pdk/validate/base_validator_spec.rb

In order to work around argument list length limits.

(PDK-985) Split validation targets into chunks of 1000

---

lib/pdk/cli/test/unit.rb

Improve the help output for `pdk test unit`'s `--verbose` flag to make
it clearer that it only affects the behaviour when used in conjunction
with `--list`. Additionally, I've added an info level log message if
`--verbose` is used without `--list` to explain that it does nothing in
this case.

(PDK-1048) Improve docs for `pdk test unit --verbose`

---

lib/pdk/module/build.rb
spec/unit/pdk/module/build_spec.rb

Before building a module package, we first call
`PDK::Test::Unit.tear_down` to make sure that there are no artifacts
left over from possible test runs. This method depends on the `rake`
binstub being present which is ensured when running `pdk test unit`,
however when the user is running `pdk build` on a clean clone of
a module this binstub is not present and the build fails.

(PDK-1061) Ensure rake binstub when building module

---

lib/pdk/validate/puppet/puppet_syntax.rb
spec/unit/pdk/validate/puppet_syntax_spec.rb

This is to fix how PDK handles unexpected errors/failures from puppet parser. Prior to this fix, these unexpected errors would cause PDK to be unable to parse the output and exit with a Ruby error/exception. Now it will read any unexpected strings from the parser and put those into the message field of a Report, which will be outputed to the user.

(PDK-1046) Improve handling of unexpected errors from puppet parser.

---

lib/pdk/report.rb
lib/pdk/report/event.rb
spec/unit/pdk/report_spec.rb

This change won't have any noticeable effect until https://github.com/rodjek/rspec-puppet/pull/706 is merged and released in 2.6.14, but is backwards compatible for safe merging.

(PDK-1051) Expose rspec-puppet coverage results to PDK

---

Gemfile
lib/pdk/validate.rb
lib/pdk/validate/base_validator.rb
lib/pdk/validate/metadata/metadata_json_lint.rb
lib/pdk/validate/puppet/puppet_lint.rb
lib/pdk/validate/ruby/rubocop.rb
spec/unit/pdk/validate/base_validator_spec.rb
spec/unit/pdk/validate/metadata_json_lint_spec.rb
spec/unit/pdk/validate/puppet_lint_spec.rb
spec/unit/pdk/validate/rubocop_spec.rb

For validators that call out to an external program, print the output from the program if `PDK::Validate::*.parse_output` fails.

(PDK-1053) Print validator output on parse_output failure

---

lib/pdk/tests/unit.rb
package-testing/spec/package/unit_test_a_new_module_spec.rb
package-testing/spec/package/version_selection_spec.rb
package-testing/spec/spec_helper_package.rb

Because of the way the parallel_tests gem invokes rspec, we need to make
sure we have generated a binstub within the module for rspec. Otherwise
when a user invokes `pdk test unit --parallel`, parallel_tests will
attempt to invoke rspec outside of the PDK-managed Ruby environment.

(PDK-1067) Ensure rspec-core binstubs are created for `pdk test unit`

---

lib/pdk/generate/module.rb
lib/pdk/generate/puppet_object.rb
lib/pdk/module/convert.rb
lib/pdk/module/templatedir.rb
spec/unit/pdk/module/convert_spec.rb

* Capture the `ArgumentError`s generated by `PDK::Module::TemplateDir` during convert and expose them nicely via the CLI.
* Add a special case to the template validation logic to detect if the user is trying to update a module that was generated using a built-in template that no longer exists.

(PDK-1041) Improve handling of errors from PDK::Module::TemplateDir

---

lib/pdk/validate/base_validator.rb
lib/pdk/validate/puppet/puppet_syntax.rb
spec/acceptance/validate_puppet_spec.rb
spec/acceptance/validate_ruby_spec.rb
spec/support/it_accepts_metadata_json_targets.rb
spec/support/it_accepts_pp_targets.rb
spec/unit/pdk/validate/base_validator_spec.rb
spec/unit/pdk/validate/rubocop_spec.rb

Update the validator to parse targets and return results as file paths
relative to the module root. This is to cut down on the character length
of the command string, since the full path of the module directory is
unnecessary and long module_root paths may end up hitting the maximum
character limit on Windows.

(PDK-1045) Send validation targets as relative file paths

---

lib/pdk/cli/exec.rb
lib/pdk/util/ruby_version.rb
spec/unit/pdk/cli/exec/command_spec.rb

Before we were appending 'bin' to the end of GEM_PATH but that did not
consider the case where GEM_PATH contains multiple paths.

(PDK-1073) Fix gem bin paths for CLI::Exec managed subprocesses

---

lib/pdk/module/build.rb
spec/unit/pdk/module/build_spec.rb

Prior to this change, every call to PDK::Module::Build#ignored_files
resulted in a Find.find enumeration of the entire module tree to test
whether or not the target_dir should be added to the ignored_files
PathSpec.
The fundamental issue was that this enumeration happened on
every call when it should have been cached after the first call, but I
also refactored the check itself to use File.realdirpath and simple
string comparisons.
Before:
```
PS>Measure-Command { bundle exec pdk build --force | Out-Default }
pdk (INFO): Building puppetlabs-windows version 5.0.0
[*] Cleaning up after running unit tests.
pdk (INFO): Build of puppetlabs-windows has completed successfully. Built package can be found here: C:/Users/pdk-dev/sandbox/puppetlabs-windows/pkg/puppetlabs-windows-5.0.0.tar.gz
Days …
```

(PDK-1088) Remove unnecessary file enumeration loop during PDK build

---

lib/pdk/generate/module.rb
lib/pdk/module/metadata.rb
spec/acceptance/test_unit_spec.rb

Dedupes the default metadata so that it only exists in one place now (PDK::Module::Metadata), which also means that generating a new module and skipping the interview will now generate the same metadata as spamming enter to accept the default values from the interview.

(PDK-585) Unify metadata defaults with/without interview

---

package-testing/Rakefile
package-testing/lib/testenv.rb
package-testing/spec/package/support/spec_utils.rb
package-testing/spec/package/unit_test_a_new_module_spec.rb
package-testing/spec/package/update_module_spec.rb

To cover the manual tests that we run on packages leading up to a release.
Also, this adds a `acceptance:testenv` rake task that quickly spins up an environment on vmpooler with PDK pre-installed.

(PDK-1077) Expand the package acceptance test suite

---

lib/pdk/cli.rb
lib/pdk/cli/test/unit.rb
lib/pdk/cli/util.rb
lib/pdk/cli/validate.rb
lib/pdk/util/puppet_version.rb
spec/acceptance/version_changer_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

Adds the `--puppet-dev` flag to `validate` and `test unit`. This flag will allow users to get Puppet from github source.

(PDK-1096, PDK-1097, PDK-1098) Add puppet-dev flag to validate and test unit

---

lib/pdk/util/puppet_version.rb
lib/pdk/util/ruby_version.rb
spec/support/packaged_install.rb
spec/unit/pdk/util/bundler_spec.rb
spec/unit/pdk/util/ruby_version_spec.rb

Simple change here to ensure that the packaged version of PDK will default to 2.4.4, but also adds a helper function to identify the newest version of Ruby in the package.

(PDK-1056) Update default ruby for packaged versions

---

package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/validate_a_new_module_spec.rb

With Puppet 6 and Ruby 2.5.1 going out soon, the new 'default' for a base package installation of PDK will be Puppet 6.0.0 and Ruby 2.5.1. This will update the package tests to expect the 2.5.1 version of the vendored lockfile.

(maint) Update package tests for ruby 2.5.1 as the new default

---

lib/pdk/module/metadata.rb
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

Metadata defaults updated to support 6.0.0.

(maint) Update PDK metadata defaults to include Puppet 6

---

lib/pdk/util.rb
spec/unit/pdk/util_spec.rb

Instead of the ArgumentError trace.

(PDK-1181) Display error when metadata.json missing or unreadable

---

lib/pdk/module/build.rb
spec/unit/pdk/module/build_spec.rb

By handling it in this manner, we can remove the need to call the PDK shipped `spec_clean` task. This is the only dependency on the PDK runtime environment when calling `PDK::Module::Build.invoke` from outside of PDK (as needs to be done in puppetlabs_spec_helper's `build` rake task).

(PDK-1100) Exclude known artifacts from build instead of cleaning

---

lib/pdk/module.rb
lib/pdk/module/build.rb
lib/pdk/validate/base_validator.rb
spec/unit/pdk/validate/base_validator_spec.rb

So things under `pkg/`, `spec/fixtures/modules` and editor-created temporary files aren't matched by the validator globbing logic.

(PDK-925) Exclude files that wouldn't be packaged from being validated

---

lib/pdk/tests/unit.rb
spec/unit/pdk/test/unit_spec.rb

Currently `pdk test unit` outputs the time rspec took to evaluate the
tests in the summary (which is always significantly shorter than the
time taken to execute the command) while `pdk test unit --parallel`
outputs the wall time for parallel_spec. This leads to a confusing
situation where running tests in parallel seems to be slower than
running the tests sequentially.
This PR changes the behaviour so that the wall time is always printed
(which is, in my humble opinion, the more useful metric in most cases).

(PDK-400) Output the rspec run wall time in test unit summary

---

lib/pdk/module/update_manager.rb
spec/unit/pdk/module/update_manager_spec.rb

```
semirhage :0: pdk/foo (git:master → origin U:1 ?:1!)$ ../bin/pdk update
pdk (INFO): Updating tsharpe-foo using the default template, from master@bcb7883 to master@bcb7883
-----------Files to be removed----------
.gitlab-ci.yml
----------------------------------------
Do you want to continue and make these changes to your module? Yes
------------Update completed------------
.
semirhage :0: pdk/foo (git:master → origin U:1 ?:1!)$ ../bin/pdk update
No changes required.
```

(PDK-972) Don't register a pending change when deleting non-existent files

---

lib/pdk/module/convert.rb
spec/unit/pdk/module/convert_spec.rb

Currently when we're updating a module's `metadata.json` file during
convert, we only replace values if they are completely absent from the
file. Unfortunately, this means if - for example - the existing metadata
defines `dependencies` as `null` or an empty array then it will not be
updated when the module is converted and it will subsequently fail to
validate cleanly.
This PR changes the metadata merging logic so that values defined as
`null` will be replaced with the default metadata value. Additionally, if the `requirements` array exists but is empty, it will also be updated with the default value.

(PDK-1093) Replace null values and empty data structures in metadata when converting

---

lib/pdk/cli/test/unit.rb
lib/pdk/cli/validate.rb
lib/pdk/tests/unit.rb
lib/pdk/util/bundler.rb
lib/pdk/util/puppet_version.rb
lib/pdk/validate/base_validator.rb
spec/acceptance/version_changer_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

Bundler requires that you continue to pass in PUPPET_GEM_VERSION
when doing check, install, and exec. Previously we were only setting
the puppet gem env when doing a bundle check and updating the lock file.

(PDK-1200) Fix bundle env handling with puppet-dev

---

lib/pdk/validate/base_validator.rb
lib/pdk/validate/puppet/puppet_syntax.rb
spec/unit/pdk/validate/puppet_syntax_spec.rb

Plan syntax validation works slightly differently to regular manifest validation. It will probably be cleaner to implement this as a separate validator rather complicate the existing Puppet syntax validator with conditional behaviour.

(PDK-1194) Exclude plans/**/*.pp from PDK::Validate::PuppetSyntax

---

.rubocop.yml
lib/pdk/answer_file.rb
lib/pdk/generate/module.rb
lib/pdk/generate/puppet_object.rb
lib/pdk/module/metadata.rb
lib/pdk/module/update_manager.rb
lib/pdk/util.rb
lib/pdk/util/filesystem.rb
lib/pdk/util/vendored_file.rb
spec/acceptance/new_module_spec.rb
spec/unit/pdk/answer_file_spec.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/generate/puppet_object_spec.rb
spec/unit/pdk/generate/task_spec.rb
spec/unit/pdk/module/update_manager_spec.rb
spec/unit/pdk/util/vendored_file_spec.rb

Consolidates all the places where PDK writes module files so that they all call a single utility method. Inside that method we open the specified file for binary writes, re-encode the content to write so that it uses universal newlines (`\n`) rather than `\r` or `\r\n` and then write it to disk.

(PDK-547) Ensure all PDK created files use LF line endings

---

lib/pdk/cli/new/module.rb
lib/pdk/generate/module.rb

For use during package build where we create modules using `pdk new
module` in order to generate the Gemfile.lock files.

(maint) Add --skip-bundle-install to `pdk new module`

---

lib/pdk/validate/base_validator.rb
lib/pdk/validate/ruby/rubocop.rb
spec/acceptance/validate_ruby_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/validate/rubocop_spec.rb

If the rubocop validator is invoked without explicitly specifying some targets, we now allow rubocop to determine its own targets (rather than using a glob in PDK to build a list of target files). This has the desirable side effect of making rubocop honour any `Exclude` patterns in `.rubocop.yml`.

(PDK-654) Allow rubocop to determine its own targets by default

---

package-testing/spec/package/add_gem_to_module_spec.rb
package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/support/install_pdk.rb
package-testing/spec/package/validate_a_new_module_spec.rb

* PDK now lays down a `Gemfile.lock` when initialising a module, so we can't expect it to be absent.
* Remove the `DEPENDENCIES` section of the `Gemfile.lock` before comparing. This section only lists the specified depedencies whereas the `GEMS` section is more important as it contains all the fully resolved dependencies. The `DEPENDENCIES` section can cause false failures in cases where different ways of specifying the dependency resolve to the same version e.g. `puppet (~> 6.0)` != `puppet (= 6.0.4)` even though they resolve to the same version.
* Either the SUITE_VERSION env var changed for OSX or the path vanagon creates changed since the last release. In any case, the path to the `.pkg` in the `.dmg` has changed and we need to update our OSX package install logic.

(maint) Fix package tests

---

lib/pdk/cli.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/new/task_spec.rb
spec/unit/pdk/module/convert_spec.rb

In most of the generators, the fact that we specify a default value for
the `--template-url` option overrides any template specified in the
metadata or `answers.json`.

(PDK-1104) Don't always override custom template url with default

---

lib/pdk/util.rb
spec/unit/pdk/util_spec.rb

The existing code doesn't handle the case where it is explicitly defined as `null` in `metadata.json`.

(PDK-1180) Cleanly handle a null pdk-version in metadata.json

---

lib/pdk/cli/bundle.rb
lib/pdk/cli/exec.rb
spec/acceptance/bundle_spec.rb

Adds a new `:pwd` context to `PDK::CLI::Exec` that behaves the same as
the `:module` context in that it sets up the Ruby environment to use the
vendored libraries, but it runs the command from the working directory
rather than the module root.
This makes `pdk bundle exec` behave more like `bundle exec`.

(PDK-1204) pdk bundle execs in the context of the pwd

---

lib/pdk/module/templatedir.rb
lib/pdk/template_file.rb
spec/unit/pdk/template_file_spec.rb

This allows templates to access configuration for other files if they really need to (for example, generating a `.puppet-lint.rc` from the checks being disabled in the `Rakefile`). The config for another file can be accessed in the template using the `config_for` method, e.g.
```erb
<%= config_for('Rakefile')['default_lint_disabled_checks'] %>
```

(PDK-1202) Pass TemplateDir object through to TemplateFile

---

lib/pdk/util.rb
spec/unit/pdk/util_spec.rb

Currently, if the template-url specified in the answer file points to
a local directory any calls to `PDK::Util.default_template_url` will
falsely report that the template is invalid even when it is a valid
template. This happens because `PDK::Util.default_template_url` only
expects the answer file to contain a template url pointing at a git
repository.

(PDK-914) Adjust default_template_url validation to accept local dirs

---

lib/pdk/util/ruby_version.rb

We should figure out a way to not have to update this every time runtime ruby version changes.

(MAINT) Bump default packaged ruby version to 2.4.5

---

lib/pdk/cli/validate.rb
lib/pdk/module.rb
lib/pdk/module/templatedir.rb
lib/pdk/validate.rb
lib/pdk/validate/base_validator.rb
lib/pdk/validate/yaml/syntax.rb
lib/pdk/validate/yaml_validator.rb
spec/spec_helper.rb
spec/support/it_accepts_metadata_json_targets.rb
spec/support/it_accepts_pp_targets.rb
spec/unit/pdk/validate/base_validator_spec.rb
spec/unit/pdk/validate/puppet_syntax_spec.rb
spec/unit/pdk/validate/rubocop_spec.rb
spec/unit/pdk/validate/tasks/name_spec.rb
spec/unit/pdk/validate/yaml/syntax_spec.rb
spec/unit/pdk/validate/yaml_validator_spec.rb

Lots of changes to unrelated spec files due to the addition of `File::FNM_DOTMATCH` when building target lists (so that the YAML validator can validate hidden files).

(PDK-735) Implement a YAML validator

---

package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/support/spec_utils.rb
package-testing/spec/package/validate_a_new_module_spec.rb

The vendored Gemfile name had a hardcoded value with the "latest ruby"
version. This caused breakage in package tests each time packaged ruby
versions were updated. This fix updates the tests to detect the latest version
from the pdk private cache.

(maint) Fix package tests to remove hardcoding

---

lib/pdk/validate/yaml/syntax.rb
spec/unit/pdk/validate/yaml/syntax_spec.rb

Ruby symbols are the only additional classes allowed in Puppet's YAML loader, so this should be the only one we need to add.

(PDK-1273) Whitelist Ruby symbols in YAML validator

---

lib/pdk/module/metadata.rb
spec/unit/pdk/module/metadata_spec.rb

By handling this during metadata.json validation/processing, it will automatically happen during `pdk convert` and `pdk update` without further changes.

(PDK-1272) Convert user/module module names to user-module

---

Gemfile

parallel 1.14.0 was just released which depends on Ruby >= 2.2

(maint) Pin parallel gem to 1.13.0

---

lib/pdk/validate/puppet/puppet_syntax.rb
spec/unit/pdk/validate/puppet_syntax_spec.rb

Puppet's parser behaves differently if the module is in `modulepath` compared to when it is not and can throw false errors in regards to files that wouldn't be loaded by the parser during normal operation (for example any smoke tests stored in `examples/**/*.pp`). By setting this value to a platform appropriate null path, we can ensure consistent behaviour.

(PDK-1266) Clear modulepath value when validating manifest syntax

---

lib/pdk/util/filesystem.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/generate/puppet_object_spec.rb
spec/unit/pdk/module/metadata_spec.rb
spec/unit/pdk/util/vendored_file_spec.rb

There are some files that PDK writes that are not derived from templates
in the pdk-templates repo. The most notable example of this is the
metadata.json file which is constructed as a Ruby hash and then
serialized to JSON and written to a file. When PDK writes these files it
was not including a trailing newline and files having trailing newlines
is a best practice.
This change updates the PDK::Util::Filesystem.write_file method to
ensure that it always writes files with a trailing newline.
Some of the unit tests around writing templated files also needed to be
updated because of the way the tests were implemented did not simulate
template files that already contained trailing newlines.

(PDK-1308) Ensure PDK-written non-templated files have trailing newline

---

.rubocop.yml

Previously running rubocop while on Windows would fail on every single file
unless the line endings were set to CRLF. This commit enforces the LF
line ending for all files, even on Windows, to keep the experience and
expectation consistent across all platforms.

(maint) Enforce line endings in Rubocop

---

lib/pdk/cli/build.rb
lib/pdk/module/metadata.rb
spec/acceptance/build_spec.rb
spec/unit/pdk/cli/build_spec.rb

If there is missing fields in the `metadata.json` when running `pdk build --force`, display an warning and continue as is expected when running with `--force`.
```
$ pdk new module foo --skip-interview
pdk (INFO): Creating new module: foo
[✔] Resolving default Gemfile dependencies.
pdk (INFO): Module 'foo' generated at path '/home/tsharpe/code/puppetlabs/pdk/foo', from template 'https://github.com/puppetlabs/pdk-templates'.
pdk (INFO): In your module directory, add classes with the 'pdk new class' command.
$ cd foo
$ pdk build --force
pdk (WARN): This module is missing the following fields in the metadata.json: summary, source, project_page, issues_url. These missing fields may affect the visibility of the module on the Forge.
pdk (INFO): Building tsharpe-foo version 0.1.0
pdk (INFO): …
```

(PDK-1086) pdk build --force to warn if necessary and continue

---

.gitignore
Gemfile

Previous people were not able to add additional gems when developing the PDK,
for example 'pry-stack_explorer', without modifying the Gemfile which could be
accidentally commited.  This commit adds the common Gemfile.local and
~/.gemfile pattern to the Gemfile.

(maint) Allow developers to add additional gems

---

lib/pdk/module/metadata.rb
lib/pdk/module/templatedir.rb
lib/pdk/util/template_uri.rb
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/module/metadata_spec.rb
spec/unit/pdk/module/update_spec.rb
spec/unit/pdk/util/template_uri_spec.rb

Currently, for packaged installations the default templates template-url
is saved in the metadata.json as the file path. This breaks when a
module that is developed with PDK on Windows is moved to a Linux installation
of PDK, since the Windows path doesn't exist. With this fix, the default
packaged template path will be determined by PDK using the keyword
'pdk-default' in that same metadata.json field and the approriate
platform specific template location will be used.
Requires #434

(PDK-1193) Saves packaged template-url in metadata as a keyword

---

lib/pdk/util/template_uri.rb
spec/unit/pdk/util/template_uri_spec.rb

DRYs up the parsing logic so that URLs passed in via `--template-url`,
`metadata.json`, or the answers file all pass through the same parsing
logic. The end result of this is that they all handle SCP style URLs in
the same way.

(PDK-1350) Handle SCP style URLs in metadata.json

---

lib/pdk/cli/test/unit.rb
lib/pdk/tests/unit.rb
spec/unit/pdk/cli/test/unit_spec.rb

Previously `pdk test unit --list` would always run under PDK's default
Ruby runtime, which could cause a Bundler error if the module had never
had `ensure_bundle` called for that runtime.

(PDK-1300) Ensure `test unit --list` uses correct Puppet/Ruby env

---

lib/pdk.rb
lib/pdk/analytics.rb
lib/pdk/cli.rb
lib/pdk/cli/util/interview.rb
lib/pdk/config.rb
lib/pdk/config/errors.rb
lib/pdk/config/json.rb
lib/pdk/config/namespace.rb
lib/pdk/config/validator.rb
lib/pdk/config/value.rb
lib/pdk/config/yaml.rb
lib/pdk/generate/module.rb
lib/pdk/logger.rb
lib/pdk/util.rb
lib/pdk/util/filesystem.rb
spec/spec_helper.rb
spec/spec_helper_acceptance.rb
spec/unit/pdk/analytics_spec.rb
spec/unit/pdk/config/json_spec.rb
spec/unit/pdk/config/namespace_spec.rb
spec/unit/pdk/config/value_spec.rb
spec/unit/pdk/config/yaml_spec.rb
spec/unit/pdk/config_spec.rb
spec/unit/pdk/util/filesystem_spec.rb
spec/unit/pdk/util_spec.rb
spec/unit/pdk_spec.rb

On the first run of PDK if the vendor-wide analytics config file is absent (`$XDG_CONFIG_HOME/puppetlabs/analytics.yml` or `%LOCALAPPDATA%/puppetlabs/analytics.yml`) the user will be greeted with the following question.
```
pdk (INFO): PDK collects anonymous usage information to help us understand how it is being used and make decisions on how to improve it. You can find out more about what data we collect and how it is used in the PDK documentation at https://puppet.com/docs/pdk/.
[Q 1/1] Do you consent to the collection of anonymous PDK usage information?
--> Yes
pdk (INFO): You can opt in or out of the usage data collection at any time by editing the analytics configuration file at /home/tsharpe/.config/puppetlabs/analytics.yml and changing the 'disabled' value.
```
If PDK is not being …

(PDK-1339) Read or interview for analytics config

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md

Not sure how to test this before merge? I guess I could merge it into master on my fork?

(MAINT) Add "needs-triage" default labels to issue templates

---

lib/pdk.rb
lib/pdk/analytics.rb
lib/pdk/analytics/client/google_analytics.rb
lib/pdk/analytics/client/noop.rb
lib/pdk/cli/new/module.rb
spec/spec_helper.rb
spec/unit/pdk/analytics/client/google_analytics_spec.rb
spec/unit/pdk/analytics/client/noop_spec.rb
spec/unit/pdk/analytics_spec.rb

Submits a single screenview during `pdk new module` for now just for testing purposes. Will be fleshed out with real events in a follow up PR.

(PDK-1341) Hook up PDK analytics to Google Analytics

---

lib/pdk/module/build.rb
spec/unit/pdk/module/build_spec.rb

Ideally we'd upgrade minitar to 0.8 which supports long paths, but the rest of the Puppet ecosystem is using minitar 0.6.1, which would result in building packages that r10k or PMT couldn't install. Also, upgrading minitar to 0.8 causes dependency hell with all the gems that have a `~> 0.6.1` minitar dependency.
Instead, we now display an error explaining the problem and asking the user to rename the file or exclude the file from the build before trying again.

(PDK-1264) Display a nicer error when tarring long paths

---

appveyor.yml

MSYS2 has dropped some packages which has broken the update process that ridk runs, causing our builds to fail. We might be able to remove this hack later on down the line when appveyor updates their images to include a newer version of msys2 by default.

Fix MSYS2 update on Appveyor

---

lib/pdk/cli/test/unit.rb
lib/pdk/cli/validate.rb
lib/pdk/generate/module.rb
lib/pdk/tests/unit.rb
spec/unit/pdk/cli/build_spec.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/new/task_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/update_spec.rb
spec/unit/pdk/cli/validate_spec.rb

This should fix up test failures and behavior changes related to this change in Cri: https://github.com/ddfreyne/cri/pull/96

(MAINT) Fix issues related to Cri behavior change with options hash

---

pdk.gemspec

cri 2.15.7 changed the behaviour of the options hash so that unspecified
flags are defaulted to an explicit `false` rather than being unset. From
the look of https://github.com/ddfreyne/cri/issues/94 though this
behaviour may be changing in the next release so lets pin cri to
a maximum of 2.15.6 for now until the behaviour stabilises and then we
can make the necessary changes.
/cc #674

(maint) Pin cri to <= 2.15.6

---

lib/pdk.rb
lib/pdk/analytics/client/google_analytics.rb
lib/pdk/cli.rb
lib/pdk/cli/build.rb
lib/pdk/cli/bundle.rb
lib/pdk/cli/convert.rb
lib/pdk/cli/new/class.rb
lib/pdk/cli/new/defined_type.rb
lib/pdk/cli/new/module.rb
lib/pdk/cli/new/provider.rb
lib/pdk/cli/new/task.rb
lib/pdk/cli/test/unit.rb
lib/pdk/cli/update.rb
lib/pdk/cli/util.rb
lib/pdk/cli/validate.rb
lib/pdk/generate/module.rb
lib/pdk/module/templatedir.rb
spec/spec_helper_acceptance.rb
spec/unit/pdk/analytics/client/google_analytics_spec.rb
spec/unit/pdk/cli/build_spec.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/new/class_spec.rb
spec/unit/pdk/cli/new/defined_type_spec.rb
spec/unit/pdk/cli/new/module_spec.rb
spec/unit/pdk/cli/new/task_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/update_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/cli_spec.rb

OK, I think this implements analytics submission for all the items that we're interested in according to our spec.
Common values that are submitted for every analytics event:
* A random non-identifying user ID (shared with Bolt analytics if installed and enabled)
* PDK version
* PDK installation method (`package` or `gem`)
* Operating system
We submit a "screen view" for every successful CLI command invocation that records:
* The command name
* The version of Ruby used to execute the PDK command
* The anonymised command options and arguments
* All arguments are redacted
* All non-boolean option values are redacted (except `--puppet-version` and `--pe-version`)
* The output formats for the command
* `PDK_*` environment variables and their values (if set)
Invalid commands are submitted as a …

(PDK-1342) Submit PDK analytics events

---

lib/pdk/util/ruby_version.rb
spec/support/packaged_install.rb

Previously the default version of ruby selected in packaged PDK instances was
hardcoded to 2.4.5 which caused issues when updating ruby runtimes and did not
reflect that the default should really by ruby 2.5 and Puppet 6.  This commit
modifies the default ruby detection to instead use the ruby environment for the
latest Puppet Gem in the PDK package install.  Non-pkged installs are not
affected.
This commit also memoizes the default value to slightly speed up default ruby
selection.

(PDK-1365) Use dynamic ruby detection for default ruby instance

---

package-testing/spec/package/update_module_spec.rb

The two modules we test `pdk update` with in the package tests pull in
additional modules which then pull in unsupported gems with compiled
extensions, causing the tests to fail.
By removing these gems from the `Gemfile` before running the tests, we can
get the tests working again while retaining the original purpose of the
tests (testing that packages that depend on beaker can be updated and
run without needing a compilation environment).
This PR combined with puppetlabs/pdk-vanagon#208 fixes up the Jenkins pipeline (see https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/16/)

(maint) Clear Gemfile overrides before pdk update test

---

package-testing/spec/package/update_module_spec.rb

Avoid undefined method `<<` on a possibly nil value during package tests.

(FIXUP) Avoid attempting to append nokogiri pin to nil in package tests

---

lib/pdk/cli.rb
spec/unit/pdk/cli_spec.rb

Previously the code would only skip the prompt if the config file
already existed or the session was deemed to be "non-interactive". This
change allows the interview to also be bypassed by setting
"PDK_DISABLE_ANALYTICS=true" and adds some tests around the opt-out
prompt behavior.

(PDK-1415) Allow analytics opt-out prompt to be disabled via ENV

---

lib/pdk/cli/util.rb
spec/unit/pdk/cli/exec/command_spec.rb
spec/unit/pdk/cli/util_spec.rb

Previously PDK detected whether a session was interactive by using the isatty
method on STDERR. However it is still possible to create TTY based STDERR in
CI environments such as Travis.  This commit adds additional Environment
Variable checks for common CI systems to ensure that PDK is non-interactive in
CI.

(PDK-1414) Detect common CI environments and set non-interactive

---

package-testing/Gemfile
package-testing/spec/package/support/install_pdk.rb
package-testing/spec/spec_helper_package.rb

Updates beaker and friends to 4.10.0 so that we can run tests against the latest platforms like RHEL8. The gem versions are all pinned because I'm paranoid about the pipeline breaking due to unrelated changes to any of these packages.
I'll link the result of the Jenkins run here once it has finished.

(maint) Update beaker in package tests

---

rakelib/command_spec.rake

Initial stab at introspecting Cri to generate a JSON spec of the PDK command structure.
/cc @glennsarti @jpogran

(PDK-1333) command_spec rake task

---

.gitignore

The /ext/packaging directory was not being excluded correctly as there appeared
to be a typo in the text.  This commit removes the `+ ` text.
[ci skip]

(maint) Fix typo in gitignore

---

rakelib/command_spec.rake

Previously the command_spec rake task only worked for older CRI version
(<= 2.11.0) because the cri_options used to be passed as a hash, but is now it's
own object type. This commit updates the conversion process to optionally
convert the object to hash on newer CRI versions.

(PDK-1333) Fix command_spec rake task for newer CRI versions

---

lib/pdk/config.rb
spec/unit/pdk/config_spec.rb

This issue was found because the classroom Windows instances created the
`~/puppetlabs/bolt/analytics.yaml` manually with UTF-16LE encoding which
Psych on Windows is unable to parse, causing
`PDK::Config.bolt_analytics_config` to raise `PDK::Config::LoadError`.
The classroom bootstrap scripts have been fixed to generate the file as
UTF-8 now, but we should still gracefully handle this case and have PDK
behave as if the file doesn't exist and use the default values.

(PDK-1434) Gracefully handle unparsable bolt analytics config

---

.rubocop_todo.yml
lib/pdk/validate/puppet/puppet_epp.rb
lib/pdk/validate/puppet_validator.rb
spec/acceptance/validate_puppet_spec.rb
spec/support/it_accepts_epp_targets.rb
spec/unit/pdk/validate/puppet/puppet_epp_spec.rb

This is a base implementation for validating EPP templates. I essentially copy/pasted the Puppet validate one, so it probably needs some pruning, but it works.

[PDK-421] Validate EPP syntax (WIP)

---

package-testing/spec/package/update_module_spec.rb

Previously in commit ea789ac02797706 the EPP validator was added however the
acceptance tests were failing.  This commit updates the acceptance test, adding
the missing validator name.

(PDK-421) Update acceptance tests for EPP Validation

---

Gemfile
lib/pdk/module/build.rb
spec/acceptance/build_spec.rb

When building module tarballs for publishing, we need to sanitise the modes of the tarball entries. Directories should have at least 0755 and files should have at least 0644.

(PDK-1309) Ensure file modes in built modules are sane

---

package-testing/spec/package/unit_test_a_new_module_spec.rb

Relax this expectation a bit so that changes in the default operatingsystem list doesn't cause false failures.

(maint) Expect pdk test unit to run more than 1 test

---

lib/pdk/cli/bundle.rb
lib/pdk/cli/exec.rb
lib/pdk/cli/exec/command.rb
lib/pdk/cli/exec/command/interactive.rb
lib/pdk/cli/exec/interactive_command.rb
package-testing/spec/package/version_selection_spec.rb
spec/acceptance/bundle_spec.rb
spec/unit/pdk/cli/exec/interactive_command_spec.rb

Previously, the subprocess invoked by `pdk bundle` had its output
streams buffered as a side effect of the subprocess infrastructure used
for other commands. Additionally, the input stream was not connected to
the subprocess at all.
This commit adds a new subclass of `PDK::CLI::Exec::Command` called
`PDK::CLI::Exec::InteractiveCommand` that bypasses all of the output
buffering, spinners, etc. that the parent class implements and instead
uses Ruby's built-in `Kernel.system` method to run the subprocess fully
interactively. The `pdk bundle` subcommand is also updated to use this
new class for invoking Bundler.
If this approach proves successful, it will likely be conditionally
extended to certain invocations of `pdk test unit` in a future PR.

(PDK-641) Make `pdk bundle` fully interactive

---

lib/pdk/cli/exec/interactive_command.rb

Changing the Kernel#system call to invoke the command directly instead
of through a shell seems to fix the missing output issue on Windows when
Powershell is invoked through Cygwin.

(FIXUP) Bypass shell invocation for PDK::CLI::Exec::InteractiveCommand

---

package-testing/Rakefile

Lets you run a single file or test through the package-testing rake tasks.

(MAINT) Allow use of RSPEC_PATTERN env var when running package tests

---

appveyor.yml

We no longer use Hipchat, so the notifications in Appveyor can be removed.

(maint) Remove Hipchat notifications

---

lib/pdk/validate/base_validator.rb
spec/unit/pdk/validate/base_validator_spec.rb

Fixes #722 
Previously if the user passed a valid directory to a validator which did not
have a pattern glob which included that directory it emitted nil targets which
then broke the validator when it tried to actually use nil.
This commit:
* Changes the directory target list from a map to a select-map to only emit
valid directory targets, instead of emitting nils.
* Removes the debug message as the actual message was incorrect. Also the file
based codepath doesn't emit debug messages, so this brings the codepath into
alignment with that.
* Adds a unit test for the scenario of passing file and directory targets into
a validator with a pattern which doesn't match any of the targets.

(GH-722) Do not emit nil targets for validators against a directory

---

.gitignore
ext/PuppetDevelopmentKit/PuppetDevelopmentKit.psd1.erb
ext/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1
ext/PuppetDevelopmentKitBeta/PuppetDevelopmentKitBeta.psd1.erb
ext/PuppetDevelopmentKitBeta/PuppetDevelopmentKitBeta.psm1.erb
rakelib/command_spec.rake

Previously the PowerShell module code lived in the pdk-vanagon repository
however during release this required manual steps.  This commit moves the
PowerShell module files to this repository and allows the use of ERB to update
them, for example, version and copyright year.
This commit also adds a beta PowerShell module which provides a much richer
and native PowerShell experience, by autogenerating from the CRI information.

(PDK-1432) Autogenerate PowerShell modules from code

---

lib/pdk/generate/module.rb
spec/unit/pdk/generate/module_spec.rb

When using `pdk new module` to create a new module, handle the
situation where the template used contains one or more files
with `delete: true` in `config_defaults.yml` instead of causing
an error.

Handle deleted template files for new module

---

lib/pdk/config.rb
lib/pdk/config/namespace.rb
lib/pdk/util/filesystem.rb
spec/unit/pdk/config/namespace_spec.rb
spec/unit/pdk/config_spec.rb

Previously even querying a configuration setting would save the default value to
disk. This is undesirable, and not expected as a user, because not all defaults
should persist on disk, across multiple PDK sessions/projects/modules. This
commit:
* Modifies the Config::Namespace class to have a new parameter called
persistent_defaults.
* Modified the [] and fetch methods in Namespace to optioally call save_data
when a default value is queried and persistent_defaults is set to true. This
is affected in #default_config_value method.
* Added a wrapper method for mkdir_p for the FileSystem class so it could be
mocked correctly in tests.  Currently it was creating folder structures in the
root of the PDK project.
* Updated the namespace and config tests to ensure that the analytics settings
use …

(PDK-1107) Config fetch and [] should have no side effects

---

lib/pdk/module/convert.rb
lib/pdk/module/metadata.rb
lib/pdk/module/templatedir.rb
lib/pdk/util/filesystem.rb
spec/acceptance/convert_spec.rb
spec/acceptance/update_spec.rb
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/module/metadata_spec.rb
spec/unit/pdk/module/update_spec.rb

During `pdk convert`, if there are init-only templates for files that do not exist in the module, create them as would be done during `pdk new module`.
Coverage dropped a bit because there isn't much in the way of unit tests for `PDK::Module::TemplateDir` currently and I don't want this change to get bogged down working on that.

(PDK-1363) Apply init templates during module convert

---

pdk.gemspec

Previously the net-ssh gem was required for beaker on older ruby versions
however this dependency is being moved to the module metagems.  This commit
removes the gem from the gemspec.

(PDK-1465) Remove net-ssh from gemspec

---

lib/pdk/cli.rb
lib/pdk/cli/config.rb
lib/pdk/cli/config/get.rb
lib/pdk/config.rb
lib/pdk/config/namespace.rb
spec/acceptance/config_get_spec.rb
spec/acceptance/config_spec.rb
spec/unit/pdk/config/namespace_spec.rb
spec/unit/pdk/config_spec.rb

---
Previously there was no way to display what the current configuration the PDK
was using.  This commit adds a `pdk config` command, with a single `get`
sub-command.
This commit also adds the ability to filter the settings either by a specific
name or setting treename.
This commit also adds tests for the new resolve method in the Namespace object.

(PDK-1107) Add pdk config get CLI command

---

Gemfile

This commit updates the minimum nokogiri version to 1.10.4 to mitigate against
CVE-2019-5477.  The PDK package will be updated in a separate commit.

(PDK-1464) Update nokogiri due to CVE-2019-5477

---

lib/pdk/cli/test/unit.rb
lib/pdk/tests/unit.rb
spec/acceptance/new_class_spec.rb
spec/acceptance/new_defined_type_spec.rb
spec/acceptance/new_provider_spec.rb
spec/acceptance/new_transport_spec.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/test/unit_spec.rb

```
semirhage :0: pdk/foo (git:pdk-680 → origin {3} ?:1!)$ ../bin/pdk test unit --interactive
pdk (INFO): Using Ruby 2.4.6
pdk (INFO): Using Puppet 6.8.1
[✔] Preparing to run the unit tests.
/home/tsharpe/.rbenv/versions/2.4.6/bin/ruby -I/home/tsharpe/.pdk/cache/ruby/2.4.0/gems/rspec-core-3.8.2/lib:/home/tsharpe/.pdk/cache/ruby/2.4.0/gems/rspec-support-3.8.2/lib /home/tsharpe/.pdk/cache/ruby/2.4.0/gems/rspec-core-3.8.2/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb
Failed to retrieve Augeas version: cannot load such file -- augeas
Run options: exclude {:bolt=>true}
foo::bar
on oraclelinux-7-x86_64
From: /home/tsharpe/code/puppetlabs/pdk/foo/spec/classes/bar_spec.rb @ line 9 :
4: describe 'foo::bar' do
5: …
```

(PDK-680) Make `pdk test unit` interactive by default

---

lib/pdk/util.rb
spec/unit/pdk/util_spec.rb

* Without this, a developer would have to piece together
the same code in multiple places to create the fixtures path
for the module.  This adds a new util method called
module_fixtures_dir that returns the ./spec/fixtures directory
of the module.

(feat) - Add new utility method for fixtures dir

---

lib/pdk/cli/util.rb

* Previously the output of the puppet and ruby version used
was displayed on every run.  This adds a new parameter to allow
for the developer to choose when this output should be displayed.
This is useful for interactive commands that would also display
the same info.
* Refactors the conditional logic used to pluck out values from the
hash using the fetch method.

(maint) - Allow no output when reading puppet_from_opts

---

Gemfile
spec/acceptance/version_changer_spec.rb

Previously the test and validate acceptance tests could fail even though the
PDK was behaving correctly, for example, incompatible Gemfile specifications
between master on Puppet and the currently released stable Puppet gem.  This
commit removes the exit code status test and instead ensures that PDK is using
the expected Puppet gem location.
---
rubyzip 2.x requires Ruby 2.4. This commit adds an upper bound in the Gemfile
for Ruby less than 2.4.

(maint) Loosen tests for puppet-dev

---

lib/pdk/util/bundler.rb

This didn't show up during the acceptance testing unfortunately.
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-van-build_adhoc/79/

(fixup) Missing require from lazy load PR

---

lib/pdk/cli/bundle.rb
package-testing/Gemfile

Previously the lazy loading of files missed the pdk/cli/exec classes.  This
commit updates the PDK CLI Bundle class to require the needed libraries.

(fixup) Fix Bundle CLI lazy load

---

lib/pdk/module/metadata.rb

(#770) Add missing require to PDK::Module::Metadata.from_file

---

pdk.gemspec

Previously the PDK used the minitar restriction similar to that of the Puppet
Windows build (~> 0.6.1).  However, from Puppet 6.10.1 this version pin
changed to `~> 0.9`. This means that using PDK as a gem on Windows, is causing
bundler to choose old versions of gems (e.g. doesn't include Litmus).
This commit changes the minitar pin to still be compatible with older Puppet
gems and still allow later Puppet too.

(PDK-1525) Use less restrictive minitar version

---

lib/pdk/generate/provider.rb

Prior to this commit, if a user creates a module with
the PDK, then tries to create a provider, they get an
error - but the error leads to an anchor on the docs
for the resource_api readme which does not exist.
This commit corrects the URL of the error message,
pointing the user to the actual instructions they need
to follow to move forward.

(MAINT) Fix new provider error message

---

.travis.yml
Gemfile
Rakefile
appveyor.yml

No significant change on the run time on Travis, but the run time on Appveyor dropped from 40 minutes to 26 minutes

(maint) Run acceptance:local tests in parallel during CI

---

lib/pdk/util.rb
spec/spec_helper.rb
spec/unit/pdk/cli/exec/interactive_command_spec.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/report_spec.rb
spec/unit/pdk/util_spec.rb
spec/unit/pdk/validate/base_validator_spec.rb
spec/unit/pdk/validate/puppet_validator_spec.rb
spec/unit/pdk/validate/tasks_validator_spec.rb

Fixes #768 
Previously the module root detection used the bare `lib` directory to detect if
a user was in a module root, without a metadata.json.  However this caused
false positives as `lib` is a very common directory. For example when in a ruby
gem project. This commit modifies the detect to use more puppet specific paths:
* lib/puppet
* lib/facter
* lib/puppet_x
This commit also adds tests for these folder directories, and uses the PDK
Filesystem abstraction classes.

(GH-768) Fix in_module_root? gives false positives

---

lib/pdk/cli.rb
lib/pdk/cli/module/generate.rb
lib/pdk/cli/util.rb
lib/pdk/cli/util/command_redirector.rb
lib/pdk/cli/util/interview.rb

After #778, update and probably other commands were broken by missing tty-prompt.
```
Traceback (most recent call last):
9: from /opt/local/bin/pdk:23:in `<main>'
8: from /opt/local/bin/pdk:23:in `load'
7: from /opt/local/lib/ruby2.5/gems/2.5.0/gems/pdk-1.15.0.pre/exe/pdk:6:in `<top (required)>'
6: from /opt/local/lib/ruby2.5/gems/2.5.0/gems/pdk-1.15.0.pre/lib/pdk/cli.rb:47:in `run'
5: from /opt/local/lib/ruby2.5/gems/2.5.0/gems/cri-2.15.9/lib/cri/command.rb:314:in `run'
4: from /opt/local/lib/ruby2.5/gems/2.5.0/gems/cri-2.15.9/lib/cri/command.rb:296:in `run'
3: from /opt/local/lib/ruby2.5/gems/2.5.0/gems/cri-2.15.9/lib/cri/command.rb:360:in `run_this'
2: from /opt/local/lib/ruby2.5/gems/2.5.0/gems/pdk-1.15.0.pre/lib/pdk/cli/update.rb:51:in `block (2 levels) in <module:CLI>'
1: from …
```

tty-prompt usage

---

lib/pdk/cli.rb
spec/unit/pdk/cli_spec.rb

Happens at the start of the global CLI runner block so that it applies
to all PDK commands.
This doesn't inform users who are purely using PDK as a library though,
but I think that they're better served by documenting the upcoming
deprecation as well as following semver and performing a major version
bump when dropping support for older Rubies.

(PDK-1519) Print deprecation notice on Ruby < 2.4

---

lib/pdk/cli/new/module.rb
spec/unit/pdk/cli/new/module_spec.rb

Exit cleanly with an error when a user tries to run `pdk new module
--skip-interview` without providing a module name in the CLI args.

(PDK-1527) Handle pdk new module --skip-interview without module name

---

Rakefile

Previously the rspec pattern between local and parallel tests was different.
This commit changes the local pattern to match that of the parallel.

(maint) Use same rspec pattern in acceptance suite

---

lib/pdk/cli/test/unit.rb
lib/pdk/tests/unit.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/test/unit_spec.rb

`pdk test unit` will now use the `progress` formatter (dots) and `pdk
test unit --verbose` will now use the `documentation` formatter.
Fixes #773

(#773) Respect --verbose in interactive pdk test unit

---

lib/pdk/cli/new/test.rb
lib/pdk/cli/test/unit.rb
lib/pdk/cli/util.rb
lib/pdk/cli/validate.rb
lib/pdk/util/puppet_version.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

The original issue was that `pdk console --puppet-dev` didn't update the
checkout before using it. This is because the CLI for `pdk console`
didn't call `PDK::Util::PuppetVersion.fetch_puppet_dev`. Rather than add
that, I've opted to add this call to the logic in
`PDK::CLI::Util.puppet_from_opts_or_env` so that it happens
automatically when setting up the environment for puppet-dev.
---
First run to seed the checkout
```
$ pdk console --puppet-dev
pdk (WARN): Module fixtures not found, please run pdk bundle exec rake spec_prep.
[✔] Installing missing Gemfile dependencies.
Ruby Version: 2.4.7
Puppet Version: 6.10.1
Puppet Debugger Version: 0.15.1
Created by: NWOps <corey@nwops.io>
Type "commands" for a list of debugger commands
or "help" to show the help screen.
1:>>
```
Manually switch …

(#764) Ensure --puppet-dev checkout is always updated

---

lib/pdk/util/filesystem.rb
spec/unit/pdk/util/filesystem_spec.rb

I can't push to the original PR and I want to ensure that this gets into the upcoming release so I've opened this PR to supercede #782 and address the review left by @glennsarti.
---
* Throws and error if the content is nil.  This fixes a problem
when a template cannot be rendered correctly due to some filesytem
issue.
This was originally seen when config_defaults.yml had a
delte: true set for any of the files.
The error message previously thrown was confusing so this is meant
to throw a better error message.

(maint) Raise error when template content is empty or nil

---

lib/pdk/config.rb
lib/pdk/config/validator.rb

Reference - #777 
Previously the PDK Analytics configuration file had a JSON schema enabled,
however the json-schema gem is causing issues.  This commit disables the schema
validation, while retaining the schema code.  Later commits will use the updated
json_schemer gem once EOL Rubies support is dropped.

(PDK-1530) Disable schema validation of config files

---

lib/pdk/util/filesystem.rb

`File.rename` (used inside of `FileUtils.mv`) raises `Errno::ENOENT`
when used inside of a VMWare shared folder on Windows. This adds
a fallback to `PDK::Util::Filesystem.mv` that first checks if the source
file exists (in case the error is legitimate) and then "moves" the file
using copy and remove operations.
As this is quite the corner case, there are no tests added but I've
tested it on a local VM and it resolves the issue.

(PDK-1169) Add VMWare fallback to PDK::Util::Filesystem.mv

---

ext/rubocop.rb
lib/pdk/cli/module/build.rb
lib/pdk/cli/module/generate.rb
spec/unit/pdk/cli/module/build_spec.rb
spec/unit/pdk/cli/module/generate_spec.rb

Added a custom RuboCop cop to detect any smart quotes that sneak in in the future. It can automatically fix smart single quotes, fixing double quotes can be implemented if needed in the future.
Fixes #806

(#806) Use ASCII quotes instead of Unicode quotes

---

lib/pdk/cli.rb
lib/pdk/cli/release.rb
lib/pdk/module.rb
lib/pdk/module/release.rb
lib/pdk/util.rb
lib/pdk/util/changelog_generator.rb
spec/unit/pdk/cli/release_spec.rb
spec/unit/pdk/module/release_spec.rb
spec/unit/pdk/util/changelog_generator_spec.rb

RFC 003 [1] defines the experience and behavior of the new pdk release sub
command.  This commit:
* Adds the root subcommand `release` with all of the available skip options.
This will allow the later `release build` and so on sub-sub-commands to be
implemented much easier. Future commits will add these sub-sub commands.
* Adds a PDK::Module::Release class which does all of the release process
* Adds tests for Release process
[1] https://github.com/puppetlabs/pdk-planning/blob/master/RFCs/0003-add-pdk-release.md

(GH-808) Implement pdk release subcommand

---

lib/pdk/cli/release.rb

Previously the pdk release command was added, however there was an issue with
the interview process raising an error.  This commit updates the interview
process to remove the error.

(GH-808) Fix prompt for pdk release

---

spec/acceptance/bundle_spec.rb

Starts an interactive `pry` session, generates some output and adds an expectation on the contents of the output. It's not the most rspecy test, but we can extract it into a matcher later if we end up creating a lot more of these tests.

(PDK-1442) Add basic interactive pdk bundle test

---

lib/pdk/cli/convert.rb
spec/acceptance/convert_spec.rb
spec/unit/pdk/cli/convert_spec.rb

Adds a simple flag for users to convert their module to the default
template.
```
pdk convert --default-template
```
is functionally equivalent to
```
pdk convert --template-url https://github.com/puppetlabs/pdk-templates
```
Additionally, it clears the saved `template-url` value so that future
operations will use the default template by default.

(PDK-1487) Add --default-template flag to pdk convert

---

lib/pdk/cli/release.rb
lib/pdk/cli/release/prep.rb
lib/pdk/cli/release/publish.rb
spec/unit/pdk/cli/release/prep_spec.rb
spec/unit/pdk/cli/release/publish_spec.rb
spec/unit/pdk/cli/release_spec.rb
spec/unit/pdk/config/namespace_spec.rb
spec/unit/pdk/module/release_spec.rb
spec/unit/pdk/util/version_spec.rb

Previously the pdk release command was added.  This commit adds the prep and
publish subcommands as per PDK RFC 003.
This commit also adds tests for new subcommands.
The `pdk release build` sub command needs more work, specifically around the tagging component.

(GH-808) Implement pdk release prep and publish subcommands

---

Gemfile

json 2.3.0 was released but there was no json_pure 2.3.0 release that we can update to and the new json gem isn't compatible with our json_pure version so we can't just bump it. json is only pulled in as a test dependency of simplecov so we'll just lock it to 2.2.0 for now.
https://github.com/flori/json/issues/393

(maint) Pin JSON test dependency to ~> 2.2.0

---

.travis.yml
Rakefile
appveyor.yml
lib/pdk/cli/exec/command.rb
lib/pdk/util/ruby_version.rb
spec/acceptance/bundle_spec.rb
spec/spec_helper_acceptance.rb
spec/unit/pdk/cli/exec/interactive_command_spec.rb
spec/unit/pdk/util/ruby_version_spec.rb

Refactor how gem_path to bundler is calculated
---
Bundler 2.1.0 now warns for many deprecations and has deprecated some methods.
The PDK needs to be modified to use the correct methods based on the version of
Bundler used.  This commit:
* Changes the command.rb to flip which Bundler method to use; preferring the new
method `.with_unbundled_env` over the deprecated `.with_clean_env`
* Updates Travis CI and Appveyor CI to run acceptance smoke tests (reduced set
of tests) on older Bundler versions to ensure that we don't break old
configuration.
* Modify Travis CI to update bundler correctly.  Previously it was not working
with the newer Bundler 2.1.0 and Travis CI worker
* Adds some TODOs for deprecated Bundler options e.g. `--path` and `--without`
* Updates the spec_helper_acceptance to …

(maint) Update methods for Bundler 2.x deprecations 

---

lib/pdk/util/env.rb
spec/unit/pdk/util/env_spec.rb

Previously the PDK Env class had case sensitive keys which meant 'PATH' could
be nil but 'Path' would have the correct value.  This commit updates the
PDK::Util::Env class to be case insensitive on Windows, by having it's own
Hash implementation. And delegates to ENV on non-windows platforms.  This
commit also adds tests for these scenarios.

(maint) Use case insensitive environment variable names on Windows

---

lib/pdk/cli/convert.rb
lib/pdk/cli/new/class.rb
lib/pdk/cli/new/defined_type.rb
lib/pdk/cli/new/provider.rb
lib/pdk/cli/new/task.rb
lib/pdk/cli/new/test.rb
lib/pdk/cli/new/transport.rb
lib/pdk/cli/update.rb
lib/pdk/generate/puppet_object.rb
lib/pdk/module/convert.rb
lib/pdk/module/update.rb
spec/acceptance/convert_spec.rb
spec/acceptance/update_spec.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/new/class_spec.rb
spec/unit/pdk/cli/new/defined_type_spec.rb
spec/unit/pdk/cli/new/task_spec.rb
spec/unit/pdk/cli/new/test_spec.rb
spec/unit/pdk/cli/update_spec.rb
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/module/update_spec.rb

Previously the `pdk new` command used the current directory as the module root
which caused errors when users executed `pdk new` when deep inside a module.
This commit changes the CLI to use the actual module root when creating the
generators, and updates the tests for this scenario.

(PDK-1556) Use the module root when generating objects

---

lib/pdk/cli/bundle.rb
spec/unit/pdk/cli/bundle_spec.rb

Up until now, when a user ran a `pdk bundle` command we would only
report a `bundle` screen view to our analytics. This resulted in us
finding out that a lot of users use `pdk bundle` but provided no insight
into why.
When a user runs `pdk bundle`, we will now capture the bundler
subcommand (but not any of the other arguments). The only exception to
this is if the user runs `pdk bundle exec` in which case we will also
capture the name of the command that is being executed (but again, none
of the arguments).
e.g.
* `pdk bundle show some_gem` will now be reported as a `bundle_show`
screen view.
* `pdk bundle exec rspec path/to/some/ruby_spec.rb` will now be
reported as a `bundle_exec_rspec` screen view.

(PDK-1588) Increase granularity of `pdk bundle` analytics

---

lib/pdk/util.rb
lib/pdk/util/windows/file.rb
spec/acceptance/bundle_spec.rb
spec/unit/pdk/config/json_schema_namespace_spec.rb
spec/unit/pdk/config/json_with_schema_spec.rb
spec/unit/pdk/config/yaml_with_schema_spec.rb
spec/unit/pdk/util_spec.rb

Currently the Package Base Directory detection uses the full path to the PDK
installation on Windows, however Bundler is very sensitive to spaces in the
directory name [1] [2].  This commit modifies the pdk_package_basedir method
to convert the path to its short name using the Windows GetShortPathNameW API
call.
Without this commit different Bundler versions on different Ruby versions may
fail to run `pdk bundle ...` style calls.
Note that the short path detection is not fool-proof.  For example if 8.3
filename creation is disabled there is no shortname to find. In that case it
just returns the long name.
This code path is not explictly tested however it is implicitly tested in the
package-testing tests as the PDK package is installed into "C:\Program Files\.."
by default.
Note that paths …

(PDK-1590) Use short-name for PDK Package base directory on Windows

---

package-testing/spec/package/version_selection_spec.rb

As the 2.4 and 2.5 runtimes have updated to use Bundler 2.x but the 2.1
runtime is stuck on Bundler 1.x, we need to remove the Gemfile.lock
manually during the version_selection package tests as Bundler 1.x hard
fails when it encounters a 2.x lockfile. This is not a problem with
other PDK commands as they update the lockfile before shelling out but
we deliberately don't do that for `pdk bundle`.

(PDK-1590) Remove Gemfile.lock before running bundle update

---

.travis.yml
Gemfile

Previously the Travis tests for license_finder were breaking in master due to
Travis configuration. Also the gem was pinned to a very old version.  This
commit updates the Travis configuration so that it correctly sets the bundler
args (can't use an empty string anymore) and updates the license_finder gem
to the latest that's compatible with Ruby 2.1.9.

(maint) Fix license_finder failures

---

lib/pdk/generate/module.rb
lib/pdk/util/template_uri.rb
spec/unit/pdk/generate/module_spec.rb

Using the default template (no saved answer, no cli override):
```
pdk (INFO): Creating new module: foo
pdk (INFO): Using the default template-uri and template-ref.
[✔] Resolving default Gemfile dependencies.
pdk (INFO): Module 'foo' generated at path '/home/tsharpe/code/puppetlabs/pdk/foo'.
pdk (INFO): In your module directory, add classes with the 'pdk new class' command.
```
Specifying the template-ref or template-url in the cli:
```
pdk (INFO): Creating new module: foo
pdk (INFO): Using the specified template-url and template-ref 'https://github.com/puppetlabs/pdk-templates#1.10.0'.
[✔] Resolving default Gemfile dependencies.
pdk (INFO): Module 'foo' generated at path '/home/tsharpe/code/puppetlabs/pdk/foo'.
pdk (INFO): In your module directory, add classes with the 'pdk new class' …
```

(PDK-1545) Include template-ref in module generation output

---

.rubocop.yml
Gemfile
spec/unit/pdk/config/json_schema_setting_spec.rb

This commit updates the development group dependences for Ruby 2.3.
---
Previously in commit 419dc51 many of the JSON Schema tests were disabled,
however one test file was missed.  This commit also skips
pdk\config\json_schema_setting_spec.rb.

(maint) Update for Ruby 2.3 and JSON Schema tests

---

.travis.yml

Concurrent-ruby 1.1.6 has a strange thread timing issue under Ruby 2.4 and the
spec/unit/pdk/analytics/util_spec.rb file. Causing facter to error with
"cannot alloc thread" which then halts the test. It doesn't occur on Appveyor
(Windows) or the regular rspec under Ruby 2.4 testing. So just use Ruby 2.5
instead.

(maint) Use Ruby 2.5 on Travis for PDK as a library tests

---

package-testing/Gemfile
package-testing/spec/package/support/spec_utils.rb

https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/107/

(PDK-1522) Update package tests for OSX 10.15

---

lib/pdk/config.rb
lib/pdk/config/ini_file.rb
lib/pdk/config/ini_file_setting.rb
lib/pdk/config/namespace.rb
spec/unit/pdk/config/ini_file_setting_spec.rb
spec/unit/pdk/config/ini_file_spec.rb

This commit adds an Ini File configuration namespace which can read and write to
Ini files. This is needed for reading environment.conf in control repositories.

(PDK-1615) Add Ini File configuration support

---

lib/pdk/cli.rb
lib/pdk/cli/config.rb
lib/pdk/cli/get.rb
lib/pdk/cli/get/config.rb
lib/pdk/config.rb
lib/pdk/config/namespace.rb
lib/pdk/config/setting.rb
lib/pdk/util.rb
spec/acceptance/get_config_spec.rb
spec/acceptance/get_spec.rb
spec/unit/pdk/config/namespace_spec.rb
spec/unit/pdk/config_spec.rb
spec/unit/pdk/util_spec.rb

~~Blocked by #849~~
---
**PDK-1607**
Previously in commit 5cb9b92 the `pdk config get` command was added however
this was in contrary to the Verb-Noun UX for the PDK CLI.  This commit:
* Copies the `pdk config` and `pdk config get` code (and tests) to be
`pdk get` and `pdk get config` respectively
* Adds deprecation notices to the `pdk config *` commands
* Updates tests for the deprecation notices
**PDK-1608**
Previously only per-user settings existed for the PDK::Config classes.  This
commit:
* Adds the concept and file locations for system level settings
* Adds helper methods to PDK::Config to make it easier to query multilevel
settings, and to query using precedence
* Makes it easier to eventually add per-project settings
* Adds tests for the new methods
* Deprecates the use of …

(PDK-1607)(PDK-1608) Implement system-level settings for PDK configuration

---

lib/pdk.rb
lib/pdk/context.rb
lib/pdk/context/control_repo.rb
lib/pdk/context/module.rb
lib/pdk/context/none.rb
lib/pdk/util.rb
spec/fixtures/control_repo/Puppetfile
spec/fixtures/control_repo/environment.conf
spec/fixtures/puppet_module/metadata.json
spec/unit/pdk/context/control_repo_spec.rb
spec/unit/pdk/context/module_spec.rb
spec/unit/pdk/context/none_spec.rb
spec/unit/pdk/context_spec.rb
spec/unit/pdk_spec.rb

Previously the PDK assumed it was always within a Puppet Module, but the PDK can
be used in far more different contexts.  This commit implements the PDK Context
RFC [1], in preparation for other parts of the PDK to consume it, for example
PDK validators:
* Adds the base Context and three concrete contexts: None, Module and
ControlRepo
* Adds a memoized context object to PDK (PDK.context), for consumption by other
parts of the PDK
* Updates the module pdk compatibility methods to accept a module path instead
of assume the PDK is always in a module. This is needed for the Module context
to check if an arbitrary module is PDK compatible
* Adds two test fixtures (a Puppet module and a control repo) for use by rspec
for contex detection
* Adds tests for context detection via …

(PDK-1612) Add PDK::Context and context detection

---

lib/pdk/config.rb
lib/pdk/context/control_repo.rb
lib/pdk/control_repo.rb
spec/support/mock_configuration.rb
spec/unit/pdk/config_spec.rb
spec/unit/pdk/context/control_repo_spec.rb
spec/unit/pdk/control_repo_spec.rb

Now that the PDK can read the environment.conf file, it can be updated to
display that the user, and be consumed by the Control Repo context. This commit:
* Adds a helper method to PDK::ControlRepo to create an an object to read/edit
an arbitrary environment.conf file.  The helper method also adds the default
settings as per Puppet documentation
* Updates the PDK::Config class to take in a PDK Context. The configuration
settings then are mutated depending on the Context, for example, the
'puppet.environment.*' settings now exist if the user is in a Control Repo,
and won't if they're in a Module.
Note that because PDK::Config now depends on a PDK::Context object being
passed in (or default via PDK.context), any method calls to configuration
information (ala PDK.config) are not allowed and …

(PDK-1614) Add project.environment settings

---

lib/pdk/util.rb
spec/unit/pdk/util_spec.rb

Pretty much what it says on the tin.

(FIXUP) Make system config path absolute instead of relative on POSIX hosts

---

package-testing/Gemfile

Does anyone remember if we were still pinning this for a reason? The last commit to touch that line was removing pinning inside the `update_module_spec` test.

(MAINT) Bump package-testing nokogiri to ~> 1.10.8

---

lib/pdk/cli.rb
lib/pdk/cli/convert.rb
lib/pdk/cli/set.rb
lib/pdk/cli/set/config.rb
lib/pdk/config.rb
lib/pdk/generate/module.rb
package-testing/spec/package/pdk_configuration_spec.rb
spec/acceptance/set_config_spec.rb
spec/acceptance/set_spec.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/set/config_spec.rb
spec/unit/pdk/config_spec.rb
spec/unit/pdk/generate/module_spec.rb
spec/unit/pdk/util/template_uri_spec.rb

Previously the PDK::Config class could only read (get) values, it could not set
them easily, and lacked logic to deal with different value types, for example
if you set a deep hash value, then the save data method on the namespace was
not triggered.
This commit:
* Adds a PDK::Config.set method which takes into account nested namespaces,
setting deep hashes, creates missing hash structures, and can add to, or
explicitly set array, values.  All of this is necessary for the CLI component
* Adds tests for the different scenarios
---
Now that the PDK::Config class now has a set method, we can add a `set config`
CLI command so users can set configuration values.  Later commits will add the
`remove config` CLI command.
This commit:
* Adds the basic `pdk set config` command
* Adds type conversion …

(PDK-1108) Add pdk set config command

---

lib/pdk/validate.rb
lib/pdk/validate/control_repo/control_repo_validator_group.rb
lib/pdk/validate/control_repo/environment_conf_validator.rb
spec/support/valid_in_context.rb
spec/unit/pdk/validate/control_repo/control_repo_validator_group_spec.rb
spec/unit/pdk/validate/control_repo/environment_conf_validator_spec.rb

This commit adds a validator for the environment.conf file when being used
inside a control repository.  The validator complies with the rules set out in
https://puppet.com/docs/puppet/latest/config_file_environment.html.
This commit also adds tests for the validator setup, and various example file
content and expected validation results.
---
TODO

(PDK-1615) Add validator for environment.conf

---

lib/pdk/validate.rb
lib/pdk/validate/invokable_validator.rb
lib/pdk/validate/validator.rb
lib/pdk/validate/validator_group.rb
spec/support/validators.rb
spec/unit/pdk/validate/validator_group_spec.rb
spec/unit/pdk/validate/validator_spec.rb
spec/unit/pdk/validate_spec.rb

Previously when a validator was created which was not valid in the PDK Context,
for example environment.conf validation in a Puppet Module, the validator would
not be invoked but a message would be logged saying that the validator had no
targets.  This is slightly confusing for users.
This commit changes the behaviour so that validators which are not valid in the
current PDK Context (Validator.is_valid_context?) are never run or have any
targets parsed.
This commit also updates the tests for these scenarios.

(PDK-1632) Only show validators that are available in the given PDK Context

---

lib/pdk/util.rb
lib/pdk/util/json_finder.rb
spec/acceptance/test_unit_spec.rb
spec/unit/pdk/util_spec.rb

This is an initial attempt at making the PDK::Util.find_valid_json_in
method tolerate unbalanced JSON fragments nested as values inside of
a larger, valid JSON document.
The simple change of making the closing brace optional allows the regex to more greedily match the largest valid document, but I would like to see this tested against more complex samples before declaring this a sufficient fix.
Resolves #821

(#821) Allow for unbalanced JSON fragments in RSpec output

---

lib/pdk/cli.rb
lib/pdk/cli/remove.rb
lib/pdk/cli/remove/config.rb
spec/acceptance/remove_config_spec.rb
spec/acceptance/remove_spec.rb
spec/unit/pdk/cli/remove/config_spec.rb

~Blocked on https://github.com/puppetlabs/pdk-planning/pull/70~
---
Now that the PDK::Config class now has a set method, we can add a `remove config`
CLI command so users can remove configuration values.
This commit:
* Adds the basic `pdk remove config` command
* Adds tests for the CLI command

(PDK-1109) Add pdk remove config

---

lib/pdk/module/convert.rb
lib/pdk/module/update.rb
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/module/update_spec.rb

Change the upgrade & convert process so that it always ensures the bundle is up to date. Depending on detecting changes to `Gemfile` is not sufficient as it doesn't detect changes to unlisted dependencies.
Fixes #869

(#869) Ensure bundle update on convert/update

---

lib/pdk/tests/unit.rb
spec/unit/pdk/test/unit_spec.rb

Fixes #828
Rake doesn't accept backslash as a path separator in the rake command line and
expects ALL paths to use forward slash as the separator.  This commit updates
the PDK::Test::Unit class to munge Windows paths prior to invoking rake.

(GH-828) Munge backslash in rake paths for unit tests

---

lib/pdk/cli/convert.rb
lib/pdk/cli/update.rb
spec/unit/pdk/cli/convert_spec.rb
spec/unit/pdk/cli/update_spec.rb

Fixes #874 
Blocking until #872 is merged due to possible merge conflicts
Previously the pdk update and convert CLI commands had a strange failure mode
where if a "module" was nested inside another "module" but only the parent had
a metadata.json. When a user tried to update or convert the child module, the
files would be put in the parent.  This was due to the CLI using the lax
detection (in_module_root?) method to "find" the module, but use the strict
detection method (module_root) during the actual conversion.
This commit updates these CLI logic to use the new PDK.context object which
is far more consistent.  This commit also adds a test for these scenarios in
PDK update and convert.

(GH-874) Use PDK Context root for PDK Convert and Update

---

lib/pdk/tests/unit.rb

Fixes issue #886
Prior to this, when specifying the path(s) to a spec file to test with the `--tests` option, PDK was failing with:
> /pdk-1.18.0/lib/pdk/tests/unit.rb:96:in `tr!': can't modify frozen String (RuntimeError)
After this, `pdk test unit --path some/spec/file.rb` works and does not throw an error.

Don't attempt to modify a frozen string when parsing '--tests' paths

---

docs/release_notes_pdk.md

This follows the convention we've been using for .z releases.

(FIXUP) Nest 1.18.1 release notess under 1.18 heading

---

lib/pdk/cli/release/publish.rb
lib/pdk/module/release.rb
spec/unit/pdk/cli/release/publish_spec.rb

@logicminds it wouldn't let me push to your fork, but I took your commit and changed a couple things:
- renamed the env var to be more consistent with existing PDK env vars
- removed the default value from the CLI help and instead just fall-back to env if CLI value is empty
- use the PDK::Util env helpers
- added unit tests
Supersedes #912

Add forge token env

---

package-testing/spec/package/version_selection_spec.rb

`puppet-debugger` 1.0.0 now included in the Ruby 2.4 dev gems doesn't support Puppet < 5.5.

(MAINT) Update version selection package tests to be more recent

---

lib/pdk/util/ruby_version.rb

There are some issues with dependencies with Bolt/Puppet under Ruby 2.7.x. This change allows us to dark-ship the Ruby 2.7.1 runtime in the PDK packages without it being activated unintentionally, even if it contains a `puppet` gem installation.

(MAINT) Default to Ruby 2.5.x on packaged installations

---

package-testing/Gemfile
package-testing/Rakefile
package-testing/config/options.rb

With this change, beaker-abs will be used instead of the vmpooler hypervisor in beaker.
In CI, since the ABS_RESOURCE_HOSTS variable is set, it will pick the existing node to run
with

Update Rakefile to use ABS as hypervisor

---

.travis.yml
package-testing/spec/package/unit_test_a_new_module_spec.rb
package-testing/spec/package/update_module_spec.rb
spec/acceptance/version_changer_spec.rb

The parallel_tests gem seems to be having trouble invoking Ruby
correctly on Windows right now, need to debug this but for now hopefully
this gets the build passing again.

(MAINT) Disable parallel unit package testing specs on Windows

---

lib/pdk/module/release.rb
spec/unit/pdk/module/release_spec.rb

Prior to this commit, a failure to publish to the forge returns the string representing a `Net::HTTPBadRequest` object instead of text including the actual error message. This commit ensures that the body of the error is instead written to the error stream.
Resolves #905

(GH-905) Ensure release failure includes error message

---

ext/build_defaults.yml

The `gpg_key` setting is overridden by the one in `build-data`. Remove the
local soon-to-be-expired GPG key from the local repo for clarity and
cleanliness.

(RE-13453) Remove old gpg key from build_defaults.yaml

---

pdk.gemspec

Previously facter was locked to 2.5.1. As we're planning to increaase the minimum supported Facter version in Puppet 7 to at least 3, we should update this in PDK as well. Otherwise, projects using the latest puppet would not be able to install PDK.

(maint) Loosen facter dependency

---

lib/pdk/module/metadata.rb

* Previously when creating a new module AIX was not
an option when choosing supported operating systems.
This resulted in many modules written with PDK to not support
AIX.  This fixes that issue by adding AIX.

Adds AIX support when creating a new module

---

lib/pdk/module/metadata.rb
spec/acceptance/build_spec.rb
spec/unit/pdk/cli/update_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

Since puppet5 is EOL, new modules should be created with up-to-date version
requirements.

Update lower puppet requirements bound when creating new modules

---

.dependency_decisions.yml
.rubocop_todo.yml
CHANGELOG.md
CONTRIBUTING.md
Gemfile
README.md
appveyor.yml
docs/customizing_module_config.md
docs/pdk_reference.md
docs/release_notes_pdk.md
ext/PuppetDevelopmentKit/PuppetDevelopmentKit.psd1.erb
ext/PuppetDevelopmentKitBeta/PuppetDevelopmentKitBeta.psd1.erb
ext/build_defaults.yml
lib/pdk/tests/unit.rb
lib/pdk/util/template_uri.rb
lib/pdk/util/vendored_file.rb
lib/pdk/validate/yaml/yaml_syntax_validator.rb
spec/acceptance/build_spec.rb
spec/acceptance/update_spec.rb
spec/acceptance/version_changer_spec.rb
spec/unit/pdk/cli/update_spec.rb
spec/unit/pdk/module/update_spec.rb
spec/unit/pdk/util/git_spec.rb
spec/unit/pdk/util/template_uri_spec.rb

Removal of any offensive or inappropriate terminology from the code base.
Update `license_finder` gem so that `whitelist` can be replaced with `:permit`
Update the running of spec tests on Appveyor; stop running on Ruby 2.1/2.3 and start running on ruby 2.5

(IAC-1438) - Removal of Inappropriate Terminology

---

.travis.yml
Gemfile
appveyor.yml
lib/pdk/tests/unit.rb
pdk.gemspec
spec/unit/pdk/module/convert_spec.rb

I have a separate branch that modernizes Rubocop and fixes all the failures but that is too big/risky this close to release, will open that after we have tagged.

(MAINT) Require Ruby >= 2.5.0 in gemspec and simplify Gemfile

---

pdk.gemspec

Forgot we still are using Ruby 2.4 for Puppet 5.5.x...

(MAINT) Drop gemspec requirement to Ruby >= 2.4.0

---

docs/pdk_install.md

- cask command option is removed in 2021
- it is now a parameter of install or upgrade
- `brew cask install` is now `brew install --cask`

Docs: Install on macOS with brew

---

lib/pdk/cli.rb
lib/pdk/cli/env.rb
spec/unit/pdk/cli/env_spec.rb

Adds an experimental `pdk env` subcommand, which aids in setting a CLI context for a specified version of Puppet.

(PF-2332) Add `pdk env` subcommand

---

docs/pdk.ditamap

The docs need version and product metadata for the new build process.

(Docs)Updating docs metadata

---

CONTRIBUTING.md

Given the introduction of [Discussions](https://github.com/puppetlabs/pdk/discussions),
we want ensure that Feature Requests are raised via the Discussions
route, rather than directly as an Issue Type.
See also: https://github.com/puppetlabs/pdk/pull/1032

(MAINT) Update CONTRIBUTING.md for new Feature Request policy

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

We are moving feature requests to Discussions and therefore should direct contributors to the Discussions area.

(MAINT) Update issue templates

---

.github/workflows/spec.yml
Gemfile
spec/spec_helper.rb

This PR adds the following test / coverage suites to a
Github Actions workflow on both Ruby 2.5 and 2.7:
- `rubocop`
- `spec:coverage`
- `license_finder`
- `test_pdk_as_library`
- `spec`
Closes: #958

(GH-958) Add Spec tests for Ruby 2.5, 2.7 on Github Actions

---

spec/unit/pdk/util_spec.rb

Prior to this commit, when running this test in the context of a
Github Actions runner, due to the `XDG_CONFIG_HOME` being set,
the PDK::Util::Env.fetch method was returning the value of this
ENV var, given it was set and did not need to return the fallback
value (2nd arg).
This commit now mocks the return PDK::Util::Env.fetch so it is
consistent whether `XDG_CONFIG_HOME` is set or not.

(MAINT) Mock PDK::Util::Env.fetch resp for util_spec.rb:292

---

.github/workflows/acceptance.yml

The new default location for Litmus's `inventory.yaml` has now
moved to `spec/fixtures/litmus_inventory.yaml`. See:
- https://github.com/puppetlabs/provision/pull/161
- https://github.com/puppetlabs/puppet_litmus/pull/396

(MAINT) Update Litmus inventory.yaml location in acceptance.yml

---

lib/pdk/cli/exec/command.rb
pdk.gemspec

Prior to this commit, it was observed on Windows Server 2016, 2019
Github Actions instances that invoking the pdk would result in
ACCESS_DENIED errors.
When the ChildProcess.leader parameter is set to true, it will set
the `CREATE_BREAKAWAY_FROM_JOB` and `JOB_OBJECT_LIMIT_BREAKAWAY_OK`
flags in the Win32. This is not required in Windows > Server 2008 / 7
and can potentially cause issues when Task Scheduler attempts to
schedule a job that invokes a program with insufficient privileges.
This commit also bumps `childprocess` to `~> 4.0.0` and `hitimes`
to `2.0.0` to resolve dependency issues after bumping `childprocess`
Closes: #1083

(GH-1083) Bump childprocess to '~> 4.0.0'; Disable @process.leader

---

lib/pdk/cli/release.rb
lib/pdk/module/release.rb
lib/pdk/util/changelog_generator.rb
spec/unit/pdk/module/release_spec.rb
spec/unit/pdk/util/changelog_generator_spec.rb

Closes https://github.com/puppetlabs/pdk/issues/917 https://github.com/puppetlabs/pdk/issues/1090

(GH-1090) Verify the changelog top most version matches the metadata version

---

lib/pdk/util/json_finder.rb
spec/acceptance/test_unit_spec.rb

Avoids throwing when `--parallel` and `--format` are used together and there are no unit tests available
Closes: #1085

(PDK-1085) Fail gracefully when no unit tests available

---

lib/pdk/cli/release.rb
spec/unit/pdk/cli/release_spec.rb

This PR contains two fixes:
Prior to this fix, the `forge-token` option defined in the PDK::CLI's
`release` subcommand did not have the `argument:` attribute set.
This meant that the underlying Cri lib treated it as a boolean option
and the forge token value was set to `true` and passed to the
`PDK::Module::Release` object.
This fix sets the `argument:` attribute with the value `:required`,
which emulates the way it is set in the `publish` subcommand.
Closes: #1113
------------------
Prior to this fix, the `forge-token` option defined in the PDK::CLI's
`release` subcommand did not have the `argument:` attribute set.
This meant that the underlying Cri lib treated it as a boolean option
and the forge token value was set to `true` and passed to the
`PDK::Module::Release` object.
This fix …

(GH-1113) (GH-917) Fix forge-token handling

---

docs/pdk_testing.md
lib/pdk/config.rb
lib/pdk/validate/invokable_validator.rb
spec/unit/pdk/config_spec.rb
spec/unit/pdk/validate/invokable_validator_spec.rb

This introduces a project level setting for a list of ignored files or patterns for the pdk validate command. Discussion: https://github.com/puppetlabs/pdk/discussions/1066
```
❯ ls foo | select name
Name
----
foo.yaml
wakka.yaml
❯ ls *.yaml  | select name
Name
----
hiera.yaml
outside.yaml
❯ pdk set config project.validate.ignore "'foo/*.yaml'"
pdk (INFO): Added new value 'foo/*.yaml' to 'project.pdk_validate.ignore'
project.pdk_validate.ignore=["foo/*.yaml"]
❯ pdk validate yaml
pdk (INFO): Using Ruby 2.7.3
pdk (INFO): Using Puppet 7.7.0
+ [X] Running yaml validators ...
|__ [X] Checking YAML syntax (**/*.yaml **/*.yml).
pdk (ERROR): yaml-syntax: Unsupported class: Tried to load unspecified class: Date (outside.yaml)
```
Closes #1118 and #1117

(GH-1118) Add ability to skip validating files

---

package-testing/Gemfile
package-testing/Rakefile
package-testing/spec/package/support/install_pdk.rb
package-testing/spec/package/support/spec_utils.rb
package-testing/spec/package/version_selection_spec.rb

These PRs came about after the introduction of new platforms and changes to packaging. 
These support the testing of built packages on the various systems both from local machine and in CI. Without these updates we are unable to verify the packaging changes being made within Vanagon or PDK-runtime.

(GH-1128) Fix package-testing issues in PDK

---

lib/pdk/util.rb
spec/unit/pdk/util_spec.rb

Prior to this change the `in_module_root` function looked only for specific folders within the project to determine if it was at the root. 
This check supplements it with a check to see if `metadata.json` is present enabling  modules that only contain `/files` without looking for such a common folder name.

(PDK-1758) supplement `in_module_root` with check for `metadata.json`

---

package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/validate_a_new_module_spec.rb

All of the pipelines have been migrated to ruby 2.7.5. This was causing some tests to fail because PDK was initialising the test modules and inferring the puppet version from the current ruby version set by RVM.. at least that is what I think was happening.
There were two tests in particular that were targeting v6 explicitly. This PR bumps them to v7 which has allowed the tests to pass.

(MAINT) Test against v7

---

lib/pdk/version.rb

This PR bumps the pdk version to 2.6.0-pre as per the post release guidance.

(PDK-1791) Bump PDK version

---

lib/pdk/util/windows/api_types.rb

When installing PDK as a rubygem on windows the following error occurs "warning: Using the last argument as keyword parameters is deprecated"
Updating with ** as per 
https://docs.knapsackpro.com/2021/fix-warning-using-the-last-argument-as-keyword-parameters-is-deprecated resolves this and PDK seems to work successfully

Fixing deprecated message on api_types.rb

---

README.md
docs/pdk_overview.md

Prior to this commit the documentation does not idenitfy the specific packages owned by Puppet vs the packages owned by the community.
This commit adds a row for in the PDK packages table and will make it easier to identify the packages that Puppet own.

(CONT-437) Identify Packages Owned By Puppet

---

spec/acceptance/version_changer_spec.rb

This commit changes the Puppet versions that are used to acceptance test the version selection feature in PDK.

(MAINT) Fix test Puppet versions

---

CHANGELOG.md
docs/pdk_known_issues.md
docs/release_notes_pdk.md
lib/pdk/version.rb

Prep for v2.6.1.
This release does not include any functional changes for the PDK gem.

(MAINT) Release prep for v2.6.1

---

package-testing/Gemfile

Nokogiri < v1.13.6 does not type-check all inputs into the XML and HTML4 SAX parsers. For CRuby users, this may allow specially crafted untrusted inputs to cause illegal memory access errors (segfault) or reads from unrelated memory.
This commit bumps the nokogiri gem used in package testing to 1.13.6.

(CONT-479) Bump nokogiri

---

lib/pdk/validate.rb
lib/pdk/validate/puppet/puppet_plan_syntax_validator.rb
lib/pdk/validate/puppet/puppet_validator_group.rb
spec/unit/pdk/validate/puppet/puppet_plan_syntax_validator_spec.rb

Puppet plans are silently ignored in `pdk validate` currently. As a Bolt user I'd like to check Bolt plan syntax before applying it.

Add Puppet validator for plans

---

Gemfile
Rakefile
package-testing/Gemfile
pdk.gemspec

In a previous change support for Ruby 2.4x was dropped.
This change contains some small dependency bumps to align.

(CONT-650) Bump dependencies

---

lib/pdk/util/changelog_generator.rb

Prior to this change `github_changelog_generator_available!` would call `bundle show github_changelog_generator` to check for the existence of the gem.
This command has been deprecated deprecated which causes the following warning to be displayed when a user runs a `release` command
`[DEPRECATED] use bundle info github_changelog_generator instead of `bundle show github_changelog_generator
This change replaces the `show` command with `info` as suggested.

(CONT-669) Use bundle info command

---

lib/pdk/version.rb

This commit ensures that the default pdk-template version is set to 2.7.2.

(CONT-694) Bump PDK Template Version

---

.github/workflows/nightly.yml
.github/workflows/release_prep.yml

Prior to this PR, the version of the gem would need to be manually updated, pushed and merged into main each time before running release_prep.yml.
This PR introduces a "version" input parameter, that can be specified when running the workflow which eliminates the need for the above.

(CONT-699) - Implement reusable workflows

---

lib/pdk/util/puppet_version.rb

Prior to this change puppet version selection via PDK_PE_VERSION would fail due to an uninitialized constant (JSON).
It would appear that 2.7 no longer lazy loads the json gem so in this change we are explicitly requiring it.

(CONT-719) Require JSON gem

---

lib/pdk/module/release.rb

As reported in #1210, in some situations pdk will fail to publish a module due to a missing require for URI.
For this specific occurance we will eventually move to the forge SDK which will elimiate the issue. However, due to some dependency constraints we cannot to that yet.
This change simply adds a new require for uri, which will solve the issue described above until we are able to migrate to the Forge SDK.

(GH-1210) Require uri

---

lib/pdk/util/ruby_version.rb

Prior to this change the packaged version of PDK would default to returning ruby 2.5.9 regardless of the latest puppet version.
This change fixes that by ensuring that we get the ruby version from the latest puppet verison by default.

(CONT-720) Fix default version selection

---

package-testing/spec/package/version_selection_spec.rb

This change updates the matrix used in the version_selection spec so that it accurately represents the versions returned by PDK when using the PDK_PUPPET_VERSION or PDK_PE_VERSION variables.

(CONT-726) Update version matrix

---

README.md

**Changes**
I asked internally if we still use the `pdk-mantainers` _at puppet dot com_, and it seems no one uses it anymore.
So I'm updating the contact information.

updates the contact information section on README

---

.github/workflows/ci.yml
Rakefile
docs/pdk_converting_modules.md
docs/pdk_creating_modules.md
lib/pdk/analytics/util.rb
lib/pdk/cli/exec/interactive_command.rb
lib/pdk/config/namespace.rb
lib/pdk/module/metadata.rb
spec/acceptance/convert_spec.rb
spec/acceptance/support/in_a_new_module.rb
spec/acceptance/test_unit_spec.rb
spec/acceptance/update_spec.rb
spec/acceptance/version_changer_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/util/puppet_version_spec.rb

This PR contains two small fixes for issues discovered while preparing the package for PDK 3.0.
Additionally, there are also some fixes for the unit and acceptance tests to allow this PR to be green.

(CONT-935) Fix issues with PDK package and tests

---

lib/pdk/tests/unit.rb

This commit adds functionality to ensure `pdk` respects the verbose option when also utilizing format options for unit testing.
* `lib/pdk/tests/unit.rb`
* Adds conditional to run `interactive_rake` command when `-v -f junit:report.xml` is passed to `pdk test unit` command.
* **Note**: Unless the first rake command contains failed events the tests will run twice; once for documentation output and again to export to specified file format(s).

(ISS-1123) Verbose output w/ junit file

---

lib/pdk/cli/bundle.rb

Prior to this change the PDK's bundle command was marked as experimental. It's been around for some time now so this tag can now be removed.

(CONT-1053) Update bundle command

---

.rubocop_todo.yml
lib/pdk/generate/module.rb
lib/pdk/module/metadata.rb

fixes for 'Take "operatingsystem_support" parameter from answer.json #1164 '

Take "operatingsystem_support" parameter from answer.json

---

package-testing/spec/package/version_selection_spec.rb

This change updates the expected Puppet versions in the package integration tests.

(MAINT) Fixup Puppet versions

---

lib/pdk/cli/util.rb
spec/unit/pdk/cli/util_spec.rb

Prior to this change compatibility warnings were out dated.
This change introduces the following:
* Update the warning message display if a module supports a version of pdk-templates that is lower than 3.0.0
* Raise an error if PDK encounters a deprecated version of Puppet

(CONT-1069) Update compatibility handling

---

lib/pdk/version.rb

This change bumps PDKs gem version to 3.0.0.
N/A
N/A
N/A

(CONT-1130) Bump PDK gem version

---

README.md
docs/pdk_overview.md
lib/pdk/cli.rb
spec/unit/pdk/cli/console_spec.rb

The console command relies on puppet-debugger which currently does not support Ruby 3 and Puppet 8.
Given that the command has always been an experimental feature of PDK, a decision was made to disable it for this release.
This will give us time to work on some updates for a later release.

(CONT-1154) Disable console command

---

docs/pdk.md
docs/pdk_install.md

Adding a registered trademark icon to the first instance of words that have been earmarked.
Prior to this commit the documentation had no trace of registered trademark icons.

(PUPDOC-5424) Adding a registered trademark icon

---

CONTRIBUTING.md
README.md
docs/pdk.md
docs/pdk_building_module_packages.md
docs/pdk_install.md
docs/pdk_reference.md
docs/pdk_testing.md

Includes context updates within README.md

(CAT-345) Update doc links where needed

---

docs/pdk_install.md

We're temporarily introducing new download links that reroute through [Scarf](https://docs.scarf.sh), a platform providing open-source maintainers with insights into project usage. This integration gathers download analytics, helping us understand how and where our software is utilized.  The new download URLs have all been manually verified and each successfully downloads the same target artifact
**Timeline:**
These changes are temporary and will be rolled back to the original links within a month. This allows us to assess metrics and strategically refine our project for even greater success.
The rollback of this PR is being managed by this issue https://github.com/puppetlabs/pdk/issues/1287

(CAT-1378) Add temporary pdk download URLs for analysis

---

package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/support/spec_utils.rb
package-testing/spec/package/validate_a_new_module_spec.rb

Update create new module tests to run against Puppet 8 rather than Puppet 7.
Successful Run: https://jenkins-platform.delivery.puppetlabs.net/view/PDK/view/pdk-vanagon/job/platform_pdk_pdk-int-sys-testing_main/SLAVE_LABEL=k8s-beaker,TEST_TARGET=windows2019-64workstation./248/console

(CAT-1601) Update Puppet test version

---

lib/pdk/cli/util/option_normalizer.rb
lib/pdk/config/namespace.rb
lib/pdk/report.rb
lib/pdk/util.rb
lib/pdk/util/puppet_version.rb
spec/support/file_based_namespaces.rb
spec/support/validators.rb

[Nightly CI](https://github.com/puppetlabs/pdk/actions/runs/7080321967/job/19268045866) is failing with the following rubocop warnings:
```ruby
Run bundle exec rubocop --format github
bundle exec rubocop --format github
shell: /usr/bin/bash -e {0}
env:
PUPPET_GEM_VERSION: ~> 7.0
Error: Lint/SymbolConversion: Unnecessary symbol conversion; use `:"write_#{format}"` instead.
Error: Style/HashEachMethods: Use `each_value` instead of `each` and remove the unused `_` block argument.
Error: Style/HashEachMethods: Use `each_value` instead of `each` and remove the unused `_tool` block argument.
Error: Style/RedundantParentheses: Don't use parentheses around a logical expression.
Error: Style/HashEachMethods: Use `each_key` instead of `each` and remove the unused `_` block argument.
Error: …
```

(maint) Fix rubocop lint warnings

---

docs/pdk_install.md

This reverts commit 85f9980e78b511306a6037e5f3e07e7ee4fb1d8e.
We temporarily introduced new download links that reroute through [Scarf](https://docs.scarf.sh): https://github.com/puppetlabs/pdk/pull/1288
This PR reverts the above.  The roll forward and backward of these links is being managed by this issue https://github.com/puppetlabs/pdk/issues/1287
------
Manually verified the preview site change.  This shows that the links have been reverted. For example https://docs-herrera-preview.netlify.app/docs/pdk/3.x/pdk_install

Revert "Add Scarf redirection links"

---

lib/pdk/module/convert.rb
lib/pdk/module/update_manager.rb
lib/pdk/template/renderer/v1/legacy_template_dir.rb
lib/pdk/template/renderer/v1/renderer.rb
lib/pdk/util/filesystem.rb
spec/unit/pdk/module/convert_spec.rb
spec/unit/pdk/module/update_manager_spec.rb
spec/unit/pdk/util/filesystem_spec.rb

This adds support for having executable templates as described in #1224. This is a duplicate of #1284 with spec tests added.
This PR makes use of a new `manage_execute_permissions` boolean config setting, which can be set on an individual template or enabled globally in the `common` config key. The existing code relied on a `:global` config setting:
https://github.com/puppetlabs/pdk/blob/4e46ce2a74acb29b1be4165e1281a7e797100dc9/lib/pdk/template/renderer/v1/legacy_template_dir.rb#L59
But as far as I can tell that key is no longer valid as neither the `Symbol` class nor the `:global` symbol are allowed during YAML parsing: https://github.com/puppetlabs/pdk/blob/4e46ce2a74acb29b1be4165e1281a7e797100dc9/lib/pdk/template/renderer/v1/legacy_template_dir.rb#L94
I noticed the current …

Support executable templates

---

.github/workflows/ci.yml
spec/spec_helper.rb

(CAT-1618) - Add Code Coverage to CI

---

spec/acceptance/remove_config_spec.rb
spec/spec_helper_acceptance.rb

(CAT-1713) Add retry to flaky tests

---

spec/acceptance/test_unit_spec.rb

(maint) - Update expected error message for test case (RSpec 3.13.0)

---

lib/pdk/cli/convert.rb
lib/pdk/cli/update.rb

Allow `pdk convert` and `pdk update` commands to be ran if  `PDK_FEATURE_FLAGS=controlrepo` set. 
```bash
$ git clone https://github.com/puppetlabs/control-repo
$ cd control-repo
$ PDK_FEATURE_FLAGS=controlrepo pdk convert
pdk (ERROR): `pdk convert` can only be run from inside a valid module directory.
```
```bash
$ git clone https://github.com/puppetlabs/control-repo
$ cd control-repo
$ PDK_FEATURE_FLAGS=controlrepo pdk convert
We need to create the metadata.json file for this module, so we're going to ask you 4 questions.
If the question is not applicable to this module, accept the default option shown after each question. You can modify any answers at any time by manually updating the metadata.json file.
[Q 1/4] If you have a Puppet Forge username, add it here.
We can use this to …
```

Allow `pdk convert` and `pdk update` to work in a ControlRepo context

---

spec/support/file_based_namespaces.rb
spec/unit/pdk/config/namespace_spec.rb
spec/unit/pdk/config/setting_spec.rb
spec/unit/pdk/config_spec.rb
spec/unit/pdk/report_spec.rb
spec/unit/pdk/template/fetcher_spec.rb
spec/unit/pdk/template/renderer/v1_spec.rb
spec/unit/pdk/template/renderer_spec.rb
spec/unit/pdk/template_spec.rb
spec/unit/pdk/util/bundler_spec.rb
spec/unit/pdk/util/vendored_file_spec.rb
spec/unit/pdk/util_spec.rb
spec/unit/pdk/validate/puppet/puppet_epp_validator_spec.rb
spec/unit/pdk/validate/puppet/puppet_plan_syntax_validator_spec.rb
spec/unit/pdk/validate/puppet/puppet_syntax_validator_spec.rb
spec/unit/pdk/validate_spec.rb
spec/unit/pdk_spec.rb

Fix rubocop warnings

---

lib/pdk/version.rb
package-testing/spec/package/update_module_spec.rb
package-testing/spec/package/version_selection_spec.rb

1. Update expected Puppet versions within the `version_selection_spec.rb`
2. Update pinned pdk-template version to match pre-release pin
3. Remove un-needed code block from `update_module_spec.rb`

(CAT-1570:CAT-1754) Version updates to code

---

package-testing/spec/package/version_selection_spec.rb

Update tests to check against installing the Major versions of the PDK. This is due to the test environment only having certain versions available to install and thus necessitating that the version be updated more often than is preferred.
With this change that is no longer necessary and the test should not need to be updated again in this manner until the release of Puppet 9.

(CAT-1628) Generalize version selection tests

---

.github/actions/workflow-restarter-proxy/action.yml

My original implentation included the `octokit` gem in my Gemfile and used this ruby library to call the github workflow_dispatch API endpoint.  However, I've now replaced this with `curl` to the same API because I don't want to change the PDK's Gemfile.  I want this restarter to be independent.  An added benefit of using the `curl` approach is that it's alot faster; no need to do a `bundle install` on each trigger of the custom action.
The following shows that the test is working causing 3 restarts:

CAT-1777: Use `curl` instead of ruby `octokit`

---

.adr-dir
.github/workflows/nightly.yml
.github/workflows/workflow-restarter.yml
docs/adr/0001-restart-pdk-nightly-on-acceptance-test-failures.md

This PR introduces the `workflow-restarter` to mitigate the intermittent failures that have been occurring for the PDK during its `nightly` workflow.  For more information on the context and solution see the [architectural design record](https://github.com/puppetlabs/pdk/blob/5d2e68ea41bc994e5ac4444576f5058b52ca2734/docs/adr/0001-restart-pdk-nightly-on-acceptance-test-failures.md).
I temporarily introduced an immediate failure on the `nightly`:
After manually triggering the `nightly`, the result was 3 retries as expected.
I rolled back this temporary change after performing the test above.

Enable pdk `nightly` workflow restarts

---

pdk.gemspec

Re-organize the dependencies within the `pdk.gemspec` to match how they are structured within the `_pdk-components.rb` in the runtime. This is to make it easier to compare and update the two simultaneously.
https://github.com/puppetlabs/puppet-runtime/blob/master/configs/projects/_pdk-components.rb

(maint) Organize dependencies within `pdk.gemspec` to match with runtime

---

package-testing/spec/package/add_gem_to_module_spec.rb

Current gem `nothing` is failing on deb/ub AARCH OSs and Fedora 36

(CAT-1900) Update Gem added by test

---

package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/validate_a_new_module_spec.rb
package-testing/spec/package/version_selection_spec.rb
package-testing/spec/spec_helper_package.rb
spec/acceptance/support/in_a_new_module.rb
spec/acceptance/version_changer_spec.rb
spec/spec_helper.rb
spec/spec_helper_acceptance.rb
spec/unit/pdk/cli/test/unit_spec.rb
spec/unit/pdk/cli/util_spec.rb
spec/unit/pdk/cli/validate_spec.rb
spec/unit/pdk/util/ruby_version_spec.rb

Set Ruby and Puppet versions used within unit, acceptance and package/integration tests to take from a hash set within their respective `spec_helper`

(CAT-1832) Globalize Puppet and Ruby versions within PDK testing framework

---

Gemfile

`rubocop-factory_bot` v2.26.0 and `rubocop-rspec_rails` v2.29.0 are both currently causing errors when run against our code and so these pins are being placed as a temporary fix while more investigation is done.
Example of error: `Property AutoCorrect of cop FactoryBot/CreateList is supposed to be a boolean and contextual is not.`

(maint) Add an exclusion pin against rubocop mocules

---

docs/pdk_install.md

Recently we removed Fedora 36 from the list of supported platforms for the PDK. This commit updates the PDK README guide to reflect that change.

(CAT-1786) Remove Fedora 36 from the and add Fedora 40 to the PDK README

---

lib/pdk/module/metadata.rb
spec/acceptance/new_module_spec.rb
spec/unit/pdk/generate/module_spec.rb

Update the OS listed as supported in a default module to more accurately match what we would expect support for each OS to be.

(CAT-1928) Update Supported OS on new module to match what is expected

---

lib/pdk/version.rb
package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/validate_a_new_module_spec.rb

Pre-release versions are needed within the templates for the pipelines to work correctly. Added notes to help visibility with this.

(CAT-1997) Update `TEMPLATE_REF` for testing purposes

---

lib/pdk/module/convert.rb
lib/pdk/template/renderer/v1/renderer.rb
spec/unit/pdk/module/convert_spec.rb

Use File::Stat.executable? instead of File.executable? when checking if template files have the execute bit to support filesystems mounted with noexec.
If the default temp directory is mounted with the `noexec` flag, `PDK::Util::Filesystem.executable?` will return `false` regardless of the execute mode bits. Using `File::Stat.executable?` instead correctly determines if the file has the execute bit set.

Support executable templates on filesystems mounted with `noexec`

---

lib/pdk/version.rb

(maint) Update pin for testing purposes

---

lib/pdk/cli/exec/command.rb
lib/pdk/cli/util.rb
lib/pdk/validate/external_command_validator.rb
lib/pdk/validate/invokable_validator.rb
lib/pdk/validate/validator_group.rb

Previously successful tasks on windows were marked with * . These changes will now tick on success, adding consistency across windows and *nix platforms.
Results from running pdk validate on a windows 10 pro vm:
Add any additional 
context about the problem here. 

(CAT-2040) pdk spinner inconsistent on windows

---

docs/release_notes_pdk.md

(DOCS) Fix typo

---

lib/pdk/util/vendored_file.rb

Link to successful test chain: https://jenkins-platform.delivery.puppetlabs.net/view/PDK/view/pdk-vanagon/job/platform_pdk_pdk-van-init_main/912/

(CAT-2007) Use vendored cert files and VERIFY_PEER wth NET::HTTP on Windows

---

lib/pdk/version.rb

Quick update to account for changes to the template gemfile

(maint) Update template ref for testing purposes

---

.github/workflows/ci.yml

Following the implementation of shellcheck in the CI, we are enabling it in the repositories we consider necessary.

(CAT-2093) Enable shellcheck in CI

---

lib/pdk/module/release.rb
pdk.gemspec
spec/unit/pdk/module/release_spec.rb

This PR adds the Forge module implementing its upload functionality instead of us maintaining our own method

(CAT-643) Add forge gem upload functionality

---

.github/workflows/nightly.yml

This PR disables the windows 2019, ruby 3.2 acceptance test in the nightly.yml.  The main reason for this is that it can potentially hide actual failures as the nightly is always red.  Therefore, I've created an internal ticket [CAT-2122](https://perforce.atlassian.net/browse/CAT-2122) to fix the issue and then rollback this PR.
-----
For example, [3 days ago our nightly.yml](https://github.com/puppetlabs/pdk/actions/runs/11430936125) looked like this, which was what we'd come to expect over the last lot of weeks:
However, [2 days ago nightly](https://github.com/puppetlabs/pdk/actions/runs/11470686046) revealed further errors (and hidden)

Disable the windows 2019 ruby 3.2 acceptance test

---

pdk.gemspec

```
Failure/Error: require 'json'
ArgumentError:
wrong number of arguments (given 1, expected 0)
```
As of the release of json v2.7.3 the above error has been occurring across the entirety of the PDK test environment.

(CAT-2130) Pin json to prevent issues

---

pdk.gemspec
spec/acceptance/report_spec.rb
spec/acceptance/validate_all_spec.rb
spec/acceptance/validate_puppet_spec.rb

Updating the tests to account for puppet-lint configuration changes to the pdk-templates brought in here: https://github.com/puppetlabs/pdk-templates/pull/600

(CAT-2121) Update tests to account for `pdk validate` changes

---

lib/pdk/util/puppet_version.rb

I've tested this locally on PEADM, but I'm not 100% certain this is a 1-1 swap. Based on the ruby implementation they should be calling the same function under the hood.
Closes #1406

(maint) Fix Gem::Platform.match() deprecation warning 

---

pdk.gemspec

This was originally added to ensure JSON would be available in all environments but should no longer necessary as JSON has been added as a default ruby gem.

(CAT-2128) Remove `json_pure` dependency

---

pdk.gemspec

Newest releases of the json gem have broken us, have temporarily pinned this while I reach out to the owners of the gem

(BUGFIX) Exclude newest JSON version

---

lib/pdk/validate/metadata/metadata_syntax_validator.rb
pdk.gemspec
spec/support/file_based_namespaces.rb
spec/unit/pdk/validate/metadata/metadata_syntax_validator_spec.rb

`JSON::Pure` no longer exists within the `json` gem as of `2.8.0` and as such this swap has to be removed.

(CAT-2155) Remove metadata_syntax_validator parser swap to `JSON::Pure`

---

docs/pdk_install.md

Due to conflicts between a newer version of GIT required to resolve a lvl9 security vulnerability and SLES 12 it looks as if we will be unable to support it, as such given that General support for it has already ended we will be dropping it from the PDK

(CAT-2162) Remove support for SLES 12

---

package-testing/spec/package/add_gem_to_module_spec.rb
package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/unprivileged_user_spec.rb
package-testing/spec/package/validate_a_new_module_spec.rb

Tests currently failing due to issues with test machines
https://jenkins-platform.delivery.puppetlabs.net/view/PDK/view/pdk-vanagon/job/platform_pdk_pdk-int-sys-testing_main/500/console

(CAT-2148) Update package testing to account for test machine changes

---

package-testing/spec/package/add_gem_to_module_spec.rb
package-testing/spec/package/airgapped_usage_spec.rb
package-testing/spec/package/unprivileged_user_spec.rb
package-testing/spec/package/validate_a_new_module_spec.rb

Reverts puppetlabs/pdk#1419
Changes where put in place to allow for a release with known issue in order to resolve a serious CVE.
Changes are to be reverted as soon as the release is made.

Revert "(CAT-2148) Update package testing to account for test machine changes"

---

docs/pdk_reference.md
docs/pdk_testing.md

(DOC) Update docs to correctly show how to specify the Puppet version

---

README.md
docs/pdk.md
docs/pdk_known_issues.md

Known issue

---

docs/pdk_known_issues.md

(DOC) Update pdk-template known issues

---

spec/unit/pdk/validate/metadata/metadata_syntax_validator_spec.rb

The error message being returned has changed, as the PDK is merely a wrapper for the JSON gem in this case and the error message is still understandable, we will simply update what is expected by the tests.

(CAT-2225) Update expected error message to account for changes to JSON

---

lib/pdk/module/update.rb

Previously the code would check only if the given tag matched the shipped pdk-templates version number. With this change it will now also first check if the given tag is a version number and then if it is check if it is greater than the shipped number.
As a note, this change is related to an info block that is given when running pdk update and has no effect on the actual function of the PDK.

(CAT-2238) Update latest_template? check to compare version numbers

---

.github/workflows/sync_private.yml

Following OSPTE-283 specification, this commit adds a Github workflow to forward PRs from the pdk to the corresponding repository.

(OSPTE-315) Adding PR forwaring workflow
